
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  UserProfile: 'UserProfile',
  Child: 'Child',
  Policy: 'Policy',
  UserPolicy: 'UserPolicy',
  Notification: 'Notification',
  Review: 'Review',
  Calculation: 'Calculation'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const UserProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  city: 'city',
  district: 'district',
  neighborhood: 'neighborhood',
  incomeLevel: 'incomeLevel',
  childCount: 'childCount',
  dualIncome: 'dualIncome',
  multiChild: 'multiChild',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserProfileScalarFieldEnum = (typeof UserProfileScalarFieldEnum)[keyof typeof UserProfileScalarFieldEnum]


export const ChildScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  name: 'name',
  birthDate: 'birthDate',
  age: 'age',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ChildScalarFieldEnum = (typeof ChildScalarFieldEnum)[keyof typeof ChildScalarFieldEnum]


export const PolicyScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  category: 'category',
  targetCity: 'targetCity',
  targetDistrict: 'targetDistrict',
  minIncomeLevel: 'minIncomeLevel',
  maxIncomeLevel: 'maxIncomeLevel',
  minChildCount: 'minChildCount',
  maxChildCount: 'maxChildCount',
  minChildAge: 'minChildAge',
  maxChildAge: 'maxChildAge',
  requiresDualIncome: 'requiresDualIncome',
  requiresMultiChild: 'requiresMultiChild',
  benefitAmount: 'benefitAmount',
  benefitType: 'benefitType',
  benefitDescription: 'benefitDescription',
  applicationStart: 'applicationStart',
  applicationEnd: 'applicationEnd',
  applicationUrl: 'applicationUrl',
  requiredDocuments: 'requiredDocuments',
  isCentralGov: 'isCentralGov',
  govLevel: 'govLevel',
  infographicUrl: 'infographicUrl',
  cardImageUrl: 'cardImageUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PolicyScalarFieldEnum = (typeof PolicyScalarFieldEnum)[keyof typeof PolicyScalarFieldEnum]


export const UserPolicyScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  policyId: 'policyId',
  isEligible: 'isEligible',
  matchScore: 'matchScore',
  isBookmarked: 'isBookmarked',
  isApplied: 'isApplied',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserPolicyScalarFieldEnum = (typeof UserPolicyScalarFieldEnum)[keyof typeof UserPolicyScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  policyId: 'policyId',
  relatedDate: 'relatedDate',
  isRead: 'isRead',
  isSent: 'isSent',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  policyId: 'policyId',
  rating: 'rating',
  title: 'title',
  content: 'content',
  tips: 'tips',
  additionalDocs: 'additionalDocs',
  isVerified: 'isVerified',
  helpfulCount: 'helpfulCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const CalculationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  calculationType: 'calculationType',
  inputData: 'inputData',
  result: 'result',
  createdAt: 'createdAt'
} as const

export type CalculationScalarFieldEnum = (typeof CalculationScalarFieldEnum)[keyof typeof CalculationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

