import { PrismaClient } from '../lib/prisma/client';
import { config } from 'dotenv';
import path from 'path';

config();

// DATABASE_URL 경로 변환
if (process.env.DATABASE_URL && process.env.DATABASE_URL.startsWith('file:./')) {
  const relativePath = process.env.DATABASE_URL.replace('file:', '');
  const absolutePath = path.join(process.cwd(), relativePath);
  process.env.DATABASE_URL = `file:${absolutePath}`;
  console.log('📁 Using database:', process.env.DATABASE_URL);
}

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 정책 데이터 시딩 시작...');
  
  // 기존 정책 개수 확인
  const existingCount = await prisma.policy.count();
  console.log(`📊 현재 데이터베이스에 ${existingCount}개의 정책이 있습니다.`);

  const policies = [
    {
      title: '아동수당',
      description: '0~7세 아동에게 월 20만원을 지급하는 정책입니다. 소득 수준과 관계없이 모든 가구가 신청할 수 있습니다.',
      category: '육아',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 7,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 200000,
      benefitType: '현금',
      benefitDescription: '월 20만원씩 매달 지급되며, 아동이 8세가 되는 달까지 지급됩니다.',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '가족관계증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '출산 축하금',
      description: '첫째 50만원, 둘째 100만원, 셋째 이상 200만원을 지급하는 지자체 정책입니다.',
      category: '출산',
      targetCity: '서울특별시',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '출생 후 1년 이내 신청 가능. 첫째 50만원, 둘째 100만원, 셋째 이상 200만원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['출생증명서', '주민등록등본', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '임신·출산 진료비 지원',
      description: '임신·출산 관련 의료비를 지원하는 정책입니다.',
      category: '출산',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 1000000,
      benefitType: '현금',
      benefitDescription: '임신·출산 진료비 최대 100만원 지원 (소득 하위 50% 가구)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['소득증명원', '의료비 영수증', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '다자녀 가구 주거 지원',
      description: '3자녀 이상 가구를 위한 주거비 지원 정책입니다.',
      category: '주거',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: 3,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: true,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '월 50만원 주거비 지원 (최대 2년)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '주거 관련 서류', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '어린이집·유치원 지원',
      description: '어린이집 및 유치원 이용료를 지원하는 정책입니다.',
      category: '교육',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 6,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '어린이집·유치원 이용료 전액 또는 일부 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '돌봄 서비스 지원',
      description: '방과후 돌봄 서비스를 지원하는 정책입니다.',
      category: '돌봄',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 6,
      maxChildAge: 12,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '초등학생 방과후 돌봄 서비스 무료 또는 저렴한 비용으로 이용',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '출산 전후 휴가 급여',
      description: '출산 전후 휴가 기간 중 급여를 지원하는 정책입니다.',
      category: '출산',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '급여',
      benefitDescription: '출산 전 90일, 출산 후 90일 휴가 기간 중 평균임금의 100% 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['출생증명서', '고용보험 가입증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '아동 급식 지원',
      description: '저소득 가구 아동의 급식비를 지원하는 정책입니다.',
      category: '육아',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 100000,
      benefitType: '현금',
      benefitDescription: '월 10만원 급식비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '다문화 가정 지원',
      description: '다문화 가정을 위한 다양한 지원 정책입니다.',
      category: '육아',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 300000,
      benefitType: '현금',
      benefitDescription: '다문화 가정 자녀 양육비 월 30만원 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '결혼증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '한부모 가정 지원',
      description: '한부모 가정을 위한 양육비 지원 정책입니다.',
      category: '육아',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 200000,
      benefitType: '현금',
      benefitDescription: '한부모 가정 자녀 양육비 월 20만원 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '한부모 가정 증명서', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '장애아동 양육 지원',
      description: '장애아동을 양육하는 가정을 위한 지원 정책입니다.',
      category: '육아',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '장애아동 양육비 월 50만원 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '장애인증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '강남구 출산 지원금',
      description: '강남구 거주 가구를 위한 출산 지원금입니다.',
      category: '출산',
      targetCity: '서울특별시',
      targetDistrict: '강남구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 1000000,
      benefitType: '현금',
      benefitDescription: '강남구 거주 가구 출산 시 100만원 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    // 추가 정책 50개
    {
      title: '아이돌봄 서비스 지원',
      description: '맞벌이 가정 등을 위해 아이돌봄 서비스를 제공하며, 소득에 따라 정부 지원을 받을 수 있습니다.',
      category: '돌봄',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 12,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '시간당 최대 3,000원 지원 (소득 수준에 따라 차등)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '청년내일채움공제',
      description: '중소·중견기업에 취업한 청년의 장기근속과 자산형성을 지원하는 제도입니다.',
      category: '고용',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '월 50만원까지 매칭 적립 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['고용계약서', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '신혼부부 전세자금 대출',
      description: '신혼부부를 대상으로 저금리로 전세자금을 대출해주는 정책입니다.',
      category: '주거',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 200000000,
      benefitType: '대출',
      benefitDescription: '최대 2억원까지 저금리 대출 (연 1.5%)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '혼인증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '청년우대형 청약통장',
      description: '청년층의 주택 마련을 돕기 위해 우대금리를 제공하는 청약통장입니다.',
      category: '주거',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '금융',
      benefitDescription: '연 2.4% 우대금리 적용',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '한부모가족 지원',
      description: '한부모가족의 생활 안정을 위해 생계비, 교육비 등을 지원합니다.',
      category: '육아',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 200000,
      benefitType: '현금',
      benefitDescription: '월 20만원 생계비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '한부모 가정 증명서', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '국민건강보험료 지원',
      description: '저소득층을 대상으로 건강보험료를 지원하여 의료 접근성을 높입니다.',
      category: '의료',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '건강보험료 전액 또는 일부 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '긴급복지 지원제도',
      description: '갑작스러운 위기 상황에 처한 가구에 생계비, 의료비 등을 신속하게 지원합니다.',
      category: '복지',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 1000000,
      benefitType: '현금',
      benefitDescription: '최대 100만원 긴급 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '위기 상황 증명서류', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '청년창업 지원사업',
      description: '청년들의 창업을 지원하기 위해 자금, 교육, 멘토링 등을 제공합니다.',
      category: '고용',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 50000000,
      benefitType: '현금',
      benefitDescription: '최대 5천만원 창업 자금 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['사업자등록증', '사업계획서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '소상공인 정책자금 지원',
      description: '소상공인의 경영 안정을 위해 저금리 대출을 지원합니다.',
      category: '경영',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 100000000,
      benefitType: '대출',
      benefitDescription: '최대 1억원 저금리 대출 (연 2.0%)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['사업자등록증', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '문화누리카드',
      description: '저소득층을 대상으로 문화·여행·스포츠 관람 등을 지원하는 카드입니다.',
      category: '문화',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 100000,
      benefitType: '현금',
      benefitDescription: '연간 10만원 문화비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '에너지 바우처',
      description: '저소득층 가구에 에너지 비용을 지원하여 난방비 부담을 덜어줍니다.',
      category: '복지',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 200000,
      benefitType: '현금',
      benefitDescription: '월 20만원 에너지비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '주거급여',
      description: '저소득층의 주거 안정을 위해 임차료나 주택 개보수 비용을 지원합니다.',
      category: '주거',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '월 50만원 주거비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '임대차계약서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '교육급여',
      description: '저소득층 학생들에게 학용품비, 교재비 등을 지원하여 교육 기회를 제공합니다.',
      category: '교육',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 6,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 100000,
      benefitType: '현금',
      benefitDescription: '월 10만원 교육비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '재학증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '국가장학금',
      description: '대학생들의 등록금 부담을 덜어주기 위해 소득 수준에 따라 장학금을 지원합니다.',
      category: '교육',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 18,
      maxChildAge: 30,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 4000000,
      benefitType: '현금',
      benefitDescription: '연간 최대 400만원 장학금 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '재학증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '취업성공패키지',
      description: '구직자에게 취업 상담, 직업훈련, 일자리 알선 등을 종합적으로 지원합니다.',
      category: '고용',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 1000000,
      benefitType: '현금',
      benefitDescription: '최대 100만원 취업 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '구직등록증', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '고용안정장려금',
      description: '기업이 근로자의 고용 안정을 위해 노력할 경우 지원금을 제공합니다.',
      category: '고용',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 5000000,
      benefitType: '현금',
      benefitDescription: '기업당 최대 500만원 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['사업자등록증', '고용계약서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '실업급여',
      description: '비자발적으로 실직한 근로자에게 일정 기간 동안 생계비를 지원합니다.',
      category: '고용',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 1500000,
      benefitType: '현금',
      benefitDescription: '월 최대 150만원 지급 (최대 9개월)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '이직증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '노인일자리 사업',
      description: '어르신들의 사회 참여와 소득 보전을 위해 일자리를 제공합니다.',
      category: '고용',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '월 50만원 일자리 소득 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '장애인 일자리 지원',
      description: '장애인의 취업을 돕기 위해 맞춤형 일자리를 지원합니다.',
      category: '고용',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '맞춤형 취업 알선 및 직업 훈련 제공',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '장애인증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '청소년 방과후 아카데미',
      description: '방과 후 돌봄이 필요한 청소년들에게 학습 지원과 체험 활동을 제공합니다.',
      category: '교육',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 12,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '방과후 학습 및 체험 프로그램 무료 제공',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '재학증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '다문화가족 지원센터 운영',
      description: '다문화가족의 안정적인 정착과 생활을 돕기 위해 다양한 서비스를 제공합니다.',
      category: '육아',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '한국어 교육, 상담, 문화 프로그램 제공',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '결혼증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '국민행복카드',
      description: '임신·출산 진료비를 지원하는 카드로, 지정된 의료기관에서 사용할 수 있습니다.',
      category: '출산',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 1000000,
      benefitType: '현금',
      benefitDescription: '임신·출산 진료비 최대 100만원 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '임신확인서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '청년희망키움통장',
      description: '일하는 청년의 자산 형성을 돕기 위해 정부가 일정 금액을 매칭하여 지원합니다.',
      category: '금융',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '월 50만원까지 매칭 적립 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '장애인 보조기기 지원',
      description: '장애인의 일상생활을 돕기 위해 보조기기 구매를 지원합니다.',
      category: '복지',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 5000000,
      benefitType: '현금',
      benefitDescription: '보조기기 구매비 최대 500만원 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '장애인증명서', '의사소견서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '한부모가족 자녀 교육비 지원',
      description: '한부모가족의 자녀 교육비를 지원하여 교육 기회를 제공합니다.',
      category: '교육',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 6,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 200000,
      benefitType: '현금',
      benefitDescription: '월 20만원 교육비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '한부모 가정 증명서', '재학증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '저소득층 자녀 학습 지원',
      description: '저소득층 가정의 자녀에게 학습 멘토링과 교육비를 지원합니다.',
      category: '교육',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 6,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 150000,
      benefitType: '현금',
      benefitDescription: '월 15만원 학습 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '재학증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '농어촌 학생 장학금',
      description: '농어촌 지역 학생들에게 장학금을 지원하여 교육 기회를 제공합니다.',
      category: '교육',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 12,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 2000000,
      benefitType: '현금',
      benefitDescription: '연간 200만원 장학금 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '재학증명서', '거주지 증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '중소기업 취업 청년 전월세 보증금 대출',
      description: '중소기업에 취업한 청년들에게 전월세 보증금을 저금리로 대출해줍니다.',
      category: '주거',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 100000000,
      benefitType: '대출',
      benefitDescription: '최대 1억원 저금리 대출 (연 1.8%)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '고용계약서', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '청년 전용 보금자리론',
      description: '청년층의 주택 구입을 돕기 위해 저금리로 주택담보대출을 제공합니다.',
      category: '주거',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 300000000,
      benefitType: '대출',
      benefitDescription: '최대 3억원 저금리 대출 (연 2.0%)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '부동산 등기부등본', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '신혼희망타운 분양 지원',
      description: '신혼부부를 대상으로 저렴한 가격에 주택을 분양합니다.',
      category: '주거',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '시세 대비 20% 할인 분양',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '혼인증명서', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '청년 월세 지원',
      description: '청년들의 주거 안정을 위해 월세를 지원하는 정책입니다.',
      category: '주거',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '월 50만원 월세 지원 (최대 2년)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '임대차계약서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '농업인 자녀 학자금 지원',
      description: '농업인의 자녀에게 대학 등록금을 지원합니다.',
      category: '교육',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 18,
      maxChildAge: 30,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 3000000,
      benefitType: '현금',
      benefitDescription: '연간 300만원 학자금 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '농업인 증명서', '재학증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '어린이집 보육료 지원',
      description: '어린이집 이용 아동의 보육료를 지원하여 부모의 부담을 덜어줍니다.',
      category: '육아',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 6,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '보육료 전액 또는 일부 지원 (소득 수준에 따라 차등)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '유치원 유아학비 지원',
      description: '유치원에 다니는 유아의 학비를 지원합니다.',
      category: '교육',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 3,
      maxChildAge: 6,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '유아학비 전액 또는 일부 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '재학증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '초등돌봄교실 운영',
      description: '맞벌이 가정을 위해 초등학생 방과 후 돌봄 서비스를 제공합니다.',
      category: '돌봄',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 6,
      maxChildAge: 12,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '방과후 돌봄 서비스 무료 제공',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '재학증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '청소년 상담복지센터 운영',
      description: '청소년의 고민 상담과 복지 서비스를 제공합니다.',
      category: '복지',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 12,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '무료 상담 및 복지 서비스 제공',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '노인복지관 운영',
      description: '어르신들의 여가 활동과 복지 서비스를 제공하는 시설입니다.',
      category: '복지',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '다양한 여가 프로그램 및 복지 서비스 제공',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '장애인 복지관 운영',
      description: '장애인의 재활과 복지를 지원하는 시설입니다.',
      category: '복지',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '재활 프로그램 및 복지 서비스 제공',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '장애인증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '여성새로일하기센터 운영',
      description: '경력 단절 여성의 취업을 지원하는 센터입니다.',
      category: '고용',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '취업 상담, 직업 훈련, 일자리 알선 제공',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '다문화가족 자녀 언어발달 지원',
      description: '다문화가족 자녀의 언어 발달을 돕기 위해 전문적인 지원을 제공합니다.',
      category: '교육',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 12,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: null,
      benefitType: '서비스',
      benefitDescription: '언어 발달 프로그램 및 전문 상담 제공',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '결혼증명서', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '국민체육진흥공단 스포츠 바우처',
      description: '저소득층 청소년에게 스포츠 활동을 지원하는 바우처를 제공합니다.',
      category: '문화',
      targetCity: null,
      targetDistrict: null,
      minIncomeLevel: '하위50%',
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 6,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 200000,
      benefitType: '현금',
      benefitDescription: '연간 20만원 스포츠 활동비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: 'https://www.gov.kr',
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '신청서']),
      isCentralGov: true,
      govLevel: '중앙',
    },
    {
      title: '서울시 출산 지원금',
      description: '서울시 거주 가구를 위한 출산 지원금입니다.',
      category: '출산',
      targetCity: '서울특별시',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 2000000,
      benefitType: '현금',
      benefitDescription: '첫째 200만원, 둘째 300만원, 셋째 이상 500만원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '부산시 다자녀 가구 지원',
      description: '부산시 거주 3자녀 이상 가구를 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '부산광역시',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: 3,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: true,
      benefitAmount: 1000000,
      benefitType: '현금',
      benefitDescription: '연간 100만원 양육비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '가족관계증명서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '경기도 신혼부부 주거 지원',
      description: '경기도 거주 신혼부부를 위한 주거 지원 정책입니다.',
      category: '주거',
      targetCity: '경기도',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 50000000,
      benefitType: '대출',
      benefitDescription: '최대 5천만원 저금리 전세자금 대출',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '혼인증명서', '소득증명원', '신청서']),
      isCentralGov: false,
      govLevel: '도',
    },
    {
      title: '인천시 한부모 가정 지원',
      description: '인천시 거주 한부모 가정을 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '인천광역시',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 300000,
      benefitType: '현금',
      benefitDescription: '월 30만원 양육비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '한부모 가정 증명서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '대구시 장애아동 지원',
      description: '대구시 거주 장애아동 가정을 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '대구광역시',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 600000,
      benefitType: '현금',
      benefitDescription: '월 60만원 장애아동 양육비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '장애인증명서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '광주시 출산 축하금',
      description: '광주시 거주 가구를 위한 출산 축하금입니다.',
      category: '출산',
      targetCity: '광주광역시',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '출산 시 50만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '대전시 다문화 가정 지원',
      description: '대전시 거주 다문화 가정을 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '대전광역시',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 400000,
      benefitType: '현금',
      benefitDescription: '월 40만원 다문화 가정 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '결혼증명서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '울산시 맞벌이 가구 지원',
      description: '울산시 거주 맞벌이 가구를 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '울산광역시',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 6,
      requiresDualIncome: true,
      requiresMultiChild: false,
      benefitAmount: 200000,
      benefitType: '현금',
      benefitDescription: '월 20만원 맞벌이 가구 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '고용계약서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '세종시 신생아 지원금',
      description: '세종시 거주 가구를 위한 신생아 지원금입니다.',
      category: '출산',
      targetCity: '세종특별자치시',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 1000000,
      benefitType: '현금',
      benefitDescription: '신생아 출생 시 100만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '강원도 출산 지원금',
      description: '강원도 거주 가구를 위한 출산 지원금입니다.',
      category: '출산',
      targetCity: '강원도',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 300000,
      benefitType: '현금',
      benefitDescription: '출산 시 30만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '도',
    },
    {
      title: '충청북도 다자녀 가구 주거 지원',
      description: '충청북도 거주 다자녀 가구를 위한 주거 지원 정책입니다.',
      category: '주거',
      targetCity: '충청북도',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: 3,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: true,
      benefitAmount: 300000,
      benefitType: '현금',
      benefitDescription: '월 30만원 주거비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '가족관계증명서', '임대차계약서', '신청서']),
      isCentralGov: false,
      govLevel: '도',
    },
    {
      title: '충청남도 한부모 가정 교육비 지원',
      description: '충청남도 거주 한부모 가정 자녀의 교육비를 지원합니다.',
      category: '교육',
      targetCity: '충청남도',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 6,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 250000,
      benefitType: '현금',
      benefitDescription: '월 25만원 교육비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '한부모 가정 증명서', '재학증명서', '신청서']),
      isCentralGov: false,
      govLevel: '도',
    },
    {
      title: '전라북도 장애아동 양육 지원',
      description: '전라북도 거주 장애아동 가정을 위한 양육 지원 정책입니다.',
      category: '육아',
      targetCity: '전라북도',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 550000,
      benefitType: '현금',
      benefitDescription: '월 55만원 장애아동 양육비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '장애인증명서', '신청서']),
      isCentralGov: false,
      govLevel: '도',
    },
    {
      title: '전라남도 다문화 가정 지원',
      description: '전라남도 거주 다문화 가정을 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '전라남도',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 350000,
      benefitType: '현금',
      benefitDescription: '월 35만원 다문화 가정 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '결혼증명서', '신청서']),
      isCentralGov: false,
      govLevel: '도',
    },
    {
      title: '경상북도 출산 축하금',
      description: '경상북도 거주 가구를 위한 출산 축하금입니다.',
      category: '출산',
      targetCity: '경상북도',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 400000,
      benefitType: '현금',
      benefitDescription: '출산 시 40만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '도',
    },
    {
      title: '경상남도 신혼부부 주거 지원',
      description: '경상남도 거주 신혼부부를 위한 주거 지원 정책입니다.',
      category: '주거',
      targetCity: '경상남도',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 40000000,
      benefitType: '대출',
      benefitDescription: '최대 4천만원 저금리 전세자금 대출',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '혼인증명서', '소득증명원', '신청서']),
      isCentralGov: false,
      govLevel: '도',
    },
    {
      title: '제주도 출산 지원금',
      description: '제주도 거주 가구를 위한 출산 지원금입니다.',
      category: '출산',
      targetCity: '제주특별자치도',
      targetDistrict: null,
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 600000,
      benefitType: '현금',
      benefitDescription: '출산 시 60만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '도',
    },
    // 지역별 추가 정책 20개
    {
      title: '서울시 강남구 육아 지원금',
      description: '강남구 거주 가구를 위한 육아 지원금입니다.',
      category: '육아',
      targetCity: '서울특별시',
      targetDistrict: '강남구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 6,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 300000,
      benefitType: '현금',
      benefitDescription: '월 30만원 육아 지원금 (최대 2년)',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '가족관계증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '서울시 서초구 다자녀 가구 지원',
      description: '서초구 거주 3자녀 이상 가구를 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '서울특별시',
      targetDistrict: '서초구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: 3,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: true,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '연간 50만원 다자녀 가구 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '가족관계증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '서울시 송파구 출산 축하금',
      description: '송파구 거주 가구를 위한 출산 축하금입니다.',
      category: '출산',
      targetCity: '서울특별시',
      targetDistrict: '송파구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 800000,
      benefitType: '현금',
      benefitDescription: '첫째 80만원, 둘째 120만원, 셋째 이상 200만원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '서울시 마포구 맞벌이 가구 지원',
      description: '마포구 거주 맞벌이 가구를 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '서울특별시',
      targetDistrict: '마포구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 6,
      requiresDualIncome: true,
      requiresMultiChild: false,
      benefitAmount: 250000,
      benefitType: '현금',
      benefitDescription: '월 25만원 맞벌이 가구 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '고용계약서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '부산시 해운대구 출산 지원금',
      description: '해운대구 거주 가구를 위한 출산 지원금입니다.',
      category: '출산',
      targetCity: '부산광역시',
      targetDistrict: '해운대구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 700000,
      benefitType: '현금',
      benefitDescription: '출산 시 70만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '부산시 사상구 한부모 가정 지원',
      description: '사상구 거주 한부모 가정을 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '부산광역시',
      targetDistrict: '사상구',
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 350000,
      benefitType: '현금',
      benefitDescription: '월 35만원 한부모 가정 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '한부모 가정 증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '대구시 수성구 다자녀 가구 주거 지원',
      description: '수성구 거주 다자녀 가구를 위한 주거 지원 정책입니다.',
      category: '주거',
      targetCity: '대구광역시',
      targetDistrict: '수성구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: 3,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: true,
      benefitAmount: 400000,
      benefitType: '현금',
      benefitDescription: '월 40만원 주거비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '가족관계증명서', '임대차계약서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '인천시 연수구 출산 축하금',
      description: '연수구 거주 가구를 위한 출산 축하금입니다.',
      category: '출산',
      targetCity: '인천광역시',
      targetDistrict: '연수구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 600000,
      benefitType: '현금',
      benefitDescription: '출산 시 60만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '경기도 수원시 영통구 육아 지원금',
      description: '영통구 거주 가구를 위한 육아 지원금입니다.',
      category: '육아',
      targetCity: '경기도',
      targetDistrict: '수원시 영통구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 6,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 200000,
      benefitType: '현금',
      benefitDescription: '월 20만원 육아 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '가족관계증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '경기도 성남시 분당구 신혼부부 주거 지원',
      description: '분당구 거주 신혼부부를 위한 주거 지원 정책입니다.',
      category: '주거',
      targetCity: '경기도',
      targetDistrict: '성남시 분당구',
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 30000000,
      benefitType: '대출',
      benefitDescription: '최대 3천만원 저금리 전세자금 대출',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '혼인증명서', '소득증명원', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '경기도 고양시 일산동구 출산 지원금',
      description: '일산동구 거주 가구를 위한 출산 지원금입니다.',
      category: '출산',
      targetCity: '경기도',
      targetDistrict: '고양시 일산동구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '출산 시 50만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '광주시 북구 다문화 가정 지원',
      description: '북구 거주 다문화 가정을 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '광주광역시',
      targetDistrict: '북구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 450000,
      benefitType: '현금',
      benefitDescription: '월 45만원 다문화 가정 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '결혼증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '대전시 유성구 장애아동 지원',
      description: '유성구 거주 장애아동 가정을 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '대전광역시',
      targetDistrict: '유성구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 650000,
      benefitType: '현금',
      benefitDescription: '월 65만원 장애아동 양육비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '장애인증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '울산시 남구 맞벌이 가구 육아 지원',
      description: '남구 거주 맞벌이 가구를 위한 육아 지원 정책입니다.',
      category: '육아',
      targetCity: '울산광역시',
      targetDistrict: '남구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 6,
      requiresDualIncome: true,
      requiresMultiChild: false,
      benefitAmount: 300000,
      benefitType: '현금',
      benefitDescription: '월 30만원 맞벌이 가구 육아 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '소득증명원', '고용계약서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '세종시 조치원읍 출산 축하금',
      description: '조치원읍 거주 가구를 위한 출산 축하금입니다.',
      category: '출산',
      targetCity: '세종특별자치시',
      targetDistrict: '조치원읍',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 900000,
      benefitType: '현금',
      benefitDescription: '출산 시 90만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '읍',
    },
    {
      title: '강원도 춘천시 출산 지원금',
      description: '춘천시 거주 가구를 위한 출산 지원금입니다.',
      category: '출산',
      targetCity: '강원도',
      targetDistrict: '춘천시',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 400000,
      benefitType: '현금',
      benefitDescription: '출산 시 40만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '충청북도 청주시 상당구 다자녀 가구 지원',
      description: '상당구 거주 다자녀 가구를 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '충청북도',
      targetDistrict: '청주시 상당구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: 3,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: true,
      benefitAmount: 600000,
      benefitType: '현금',
      benefitDescription: '연간 60만원 다자녀 가구 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '가족관계증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '충청남도 천안시 동남구 한부모 가정 교육비 지원',
      description: '동남구 거주 한부모 가정 자녀의 교육비를 지원합니다.',
      category: '교육',
      targetCity: '충청남도',
      targetDistrict: '천안시 동남구',
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 6,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 300000,
      benefitType: '현금',
      benefitDescription: '월 30만원 교육비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '한부모 가정 증명서', '재학증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '전라북도 전주시 완산구 출산 축하금',
      description: '완산구 거주 가구를 위한 출산 축하금입니다.',
      category: '출산',
      targetCity: '전라북도',
      targetDistrict: '전주시 완산구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '출산 시 50만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '전라남도 목포시 장애아동 양육 지원',
      description: '목포시 거주 장애아동 가정을 위한 양육 지원 정책입니다.',
      category: '육아',
      targetCity: '전라남도',
      targetDistrict: '목포시',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: 0,
      maxChildAge: 18,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 600000,
      benefitType: '현금',
      benefitDescription: '월 60만원 장애아동 양육비 지원',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '장애인증명서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
    {
      title: '경상북도 포항시 남구 신혼부부 주거 지원',
      description: '남구 거주 신혼부부를 위한 주거 지원 정책입니다.',
      category: '주거',
      targetCity: '경상북도',
      targetDistrict: '포항시 남구',
      minIncomeLevel: null,
      maxIncomeLevel: '중위50-100%',
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 25000000,
      benefitType: '대출',
      benefitDescription: '최대 2천5백만원 저금리 전세자금 대출',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '혼인증명서', '소득증명원', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '경상남도 창원시 의창구 출산 지원금',
      description: '의창구 거주 가구를 위한 출산 지원금입니다.',
      category: '출산',
      targetCity: '경상남도',
      targetDistrict: '창원시 의창구',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 550000,
      benefitType: '현금',
      benefitDescription: '출산 시 55만원 지급',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '출생증명서', '신청서']),
      isCentralGov: false,
      govLevel: '구',
    },
    {
      title: '제주도 제주시 다문화 가정 지원',
      description: '제주시 거주 다문화 가정을 위한 지원 정책입니다.',
      category: '육아',
      targetCity: '제주특별자치도',
      targetDistrict: '제주시',
      minIncomeLevel: null,
      maxIncomeLevel: null,
      minChildCount: null,
      maxChildCount: null,
      minChildAge: null,
      maxChildAge: null,
      requiresDualIncome: false,
      requiresMultiChild: false,
      benefitAmount: 500000,
      benefitType: '현금',
      benefitDescription: '월 50만원 다문화 가정 지원금',
      applicationStart: null,
      applicationEnd: null,
      applicationUrl: null,
      requiredDocuments: JSON.stringify(['주민등록등본', '결혼증명서', '신청서']),
      isCentralGov: false,
      govLevel: '시',
    },
  ];

  // 기존 정책 모두 삭제 (선택사항 - 주석 처리하면 중복 방지)
  // await prisma.policy.deleteMany({});
  // console.log('🗑️  기존 정책 삭제됨');

  for (const policy of policies) {
    const existing = await prisma.policy.findFirst({
      where: { title: policy.title },
    });

    if (!existing) {
      await prisma.policy.create({
        data: policy,
      });
      console.log(`✅ ${policy.title} 추가됨`);
    } else {
      console.log(`⏭️  ${policy.title} 이미 존재함`);
    }
  }
  
  // 최종 개수 확인
  const finalCount = await prisma.policy.count();
  console.log(`📊 시딩 완료 후 총 ${finalCount}개의 정책이 있습니다.`);

  console.log('🎉 정책 데이터 시딩 완료!');
}

main()
  .catch((e) => {
    console.error('❌ 시딩 중 오류 발생:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

