
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Calculation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Calculation
 * 
 */
export type CalculationModel = runtime.Types.Result.DefaultSelection<Prisma.$CalculationPayload>

export type AggregateCalculation = {
  _count: CalculationCountAggregateOutputType | null
  _min: CalculationMinAggregateOutputType | null
  _max: CalculationMaxAggregateOutputType | null
}

export type CalculationMinAggregateOutputType = {
  id: string | null
  userId: string | null
  calculationType: string | null
  inputData: string | null
  result: string | null
  createdAt: Date | null
}

export type CalculationMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  calculationType: string | null
  inputData: string | null
  result: string | null
  createdAt: Date | null
}

export type CalculationCountAggregateOutputType = {
  id: number
  userId: number
  calculationType: number
  inputData: number
  result: number
  createdAt: number
  _all: number
}


export type CalculationMinAggregateInputType = {
  id?: true
  userId?: true
  calculationType?: true
  inputData?: true
  result?: true
  createdAt?: true
}

export type CalculationMaxAggregateInputType = {
  id?: true
  userId?: true
  calculationType?: true
  inputData?: true
  result?: true
  createdAt?: true
}

export type CalculationCountAggregateInputType = {
  id?: true
  userId?: true
  calculationType?: true
  inputData?: true
  result?: true
  createdAt?: true
  _all?: true
}

export type CalculationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Calculation to aggregate.
   */
  where?: Prisma.CalculationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Calculations to fetch.
   */
  orderBy?: Prisma.CalculationOrderByWithRelationInput | Prisma.CalculationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CalculationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Calculations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Calculations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Calculations
  **/
  _count?: true | CalculationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CalculationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CalculationMaxAggregateInputType
}

export type GetCalculationAggregateType<T extends CalculationAggregateArgs> = {
      [P in keyof T & keyof AggregateCalculation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCalculation[P]>
    : Prisma.GetScalarType<T[P], AggregateCalculation[P]>
}




export type CalculationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CalculationWhereInput
  orderBy?: Prisma.CalculationOrderByWithAggregationInput | Prisma.CalculationOrderByWithAggregationInput[]
  by: Prisma.CalculationScalarFieldEnum[] | Prisma.CalculationScalarFieldEnum
  having?: Prisma.CalculationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CalculationCountAggregateInputType | true
  _min?: CalculationMinAggregateInputType
  _max?: CalculationMaxAggregateInputType
}

export type CalculationGroupByOutputType = {
  id: string
  userId: string
  calculationType: string
  inputData: string
  result: string
  createdAt: Date
  _count: CalculationCountAggregateOutputType | null
  _min: CalculationMinAggregateOutputType | null
  _max: CalculationMaxAggregateOutputType | null
}

type GetCalculationGroupByPayload<T extends CalculationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CalculationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CalculationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CalculationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CalculationGroupByOutputType[P]>
      }
    >
  >



export type CalculationWhereInput = {
  AND?: Prisma.CalculationWhereInput | Prisma.CalculationWhereInput[]
  OR?: Prisma.CalculationWhereInput[]
  NOT?: Prisma.CalculationWhereInput | Prisma.CalculationWhereInput[]
  id?: Prisma.StringFilter<"Calculation"> | string
  userId?: Prisma.StringFilter<"Calculation"> | string
  calculationType?: Prisma.StringFilter<"Calculation"> | string
  inputData?: Prisma.StringFilter<"Calculation"> | string
  result?: Prisma.StringFilter<"Calculation"> | string
  createdAt?: Prisma.DateTimeFilter<"Calculation"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type CalculationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  calculationType?: Prisma.SortOrder
  inputData?: Prisma.SortOrder
  result?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type CalculationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CalculationWhereInput | Prisma.CalculationWhereInput[]
  OR?: Prisma.CalculationWhereInput[]
  NOT?: Prisma.CalculationWhereInput | Prisma.CalculationWhereInput[]
  userId?: Prisma.StringFilter<"Calculation"> | string
  calculationType?: Prisma.StringFilter<"Calculation"> | string
  inputData?: Prisma.StringFilter<"Calculation"> | string
  result?: Prisma.StringFilter<"Calculation"> | string
  createdAt?: Prisma.DateTimeFilter<"Calculation"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type CalculationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  calculationType?: Prisma.SortOrder
  inputData?: Prisma.SortOrder
  result?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CalculationCountOrderByAggregateInput
  _max?: Prisma.CalculationMaxOrderByAggregateInput
  _min?: Prisma.CalculationMinOrderByAggregateInput
}

export type CalculationScalarWhereWithAggregatesInput = {
  AND?: Prisma.CalculationScalarWhereWithAggregatesInput | Prisma.CalculationScalarWhereWithAggregatesInput[]
  OR?: Prisma.CalculationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CalculationScalarWhereWithAggregatesInput | Prisma.CalculationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Calculation"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Calculation"> | string
  calculationType?: Prisma.StringWithAggregatesFilter<"Calculation"> | string
  inputData?: Prisma.StringWithAggregatesFilter<"Calculation"> | string
  result?: Prisma.StringWithAggregatesFilter<"Calculation"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Calculation"> | Date | string
}

export type CalculationCreateInput = {
  id?: string
  calculationType: string
  inputData: string
  result: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCalculationsInput
}

export type CalculationUncheckedCreateInput = {
  id?: string
  userId: string
  calculationType: string
  inputData: string
  result: string
  createdAt?: Date | string
}

export type CalculationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calculationType?: Prisma.StringFieldUpdateOperationsInput | string
  inputData?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCalculationsNestedInput
}

export type CalculationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  calculationType?: Prisma.StringFieldUpdateOperationsInput | string
  inputData?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CalculationCreateManyInput = {
  id?: string
  userId: string
  calculationType: string
  inputData: string
  result: string
  createdAt?: Date | string
}

export type CalculationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calculationType?: Prisma.StringFieldUpdateOperationsInput | string
  inputData?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CalculationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  calculationType?: Prisma.StringFieldUpdateOperationsInput | string
  inputData?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CalculationListRelationFilter = {
  every?: Prisma.CalculationWhereInput
  some?: Prisma.CalculationWhereInput
  none?: Prisma.CalculationWhereInput
}

export type CalculationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CalculationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  calculationType?: Prisma.SortOrder
  inputData?: Prisma.SortOrder
  result?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CalculationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  calculationType?: Prisma.SortOrder
  inputData?: Prisma.SortOrder
  result?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CalculationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  calculationType?: Prisma.SortOrder
  inputData?: Prisma.SortOrder
  result?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CalculationCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CalculationCreateWithoutUserInput, Prisma.CalculationUncheckedCreateWithoutUserInput> | Prisma.CalculationCreateWithoutUserInput[] | Prisma.CalculationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CalculationCreateOrConnectWithoutUserInput | Prisma.CalculationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CalculationCreateManyUserInputEnvelope
  connect?: Prisma.CalculationWhereUniqueInput | Prisma.CalculationWhereUniqueInput[]
}

export type CalculationUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CalculationCreateWithoutUserInput, Prisma.CalculationUncheckedCreateWithoutUserInput> | Prisma.CalculationCreateWithoutUserInput[] | Prisma.CalculationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CalculationCreateOrConnectWithoutUserInput | Prisma.CalculationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CalculationCreateManyUserInputEnvelope
  connect?: Prisma.CalculationWhereUniqueInput | Prisma.CalculationWhereUniqueInput[]
}

export type CalculationUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CalculationCreateWithoutUserInput, Prisma.CalculationUncheckedCreateWithoutUserInput> | Prisma.CalculationCreateWithoutUserInput[] | Prisma.CalculationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CalculationCreateOrConnectWithoutUserInput | Prisma.CalculationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CalculationUpsertWithWhereUniqueWithoutUserInput | Prisma.CalculationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CalculationCreateManyUserInputEnvelope
  set?: Prisma.CalculationWhereUniqueInput | Prisma.CalculationWhereUniqueInput[]
  disconnect?: Prisma.CalculationWhereUniqueInput | Prisma.CalculationWhereUniqueInput[]
  delete?: Prisma.CalculationWhereUniqueInput | Prisma.CalculationWhereUniqueInput[]
  connect?: Prisma.CalculationWhereUniqueInput | Prisma.CalculationWhereUniqueInput[]
  update?: Prisma.CalculationUpdateWithWhereUniqueWithoutUserInput | Prisma.CalculationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CalculationUpdateManyWithWhereWithoutUserInput | Prisma.CalculationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CalculationScalarWhereInput | Prisma.CalculationScalarWhereInput[]
}

export type CalculationUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CalculationCreateWithoutUserInput, Prisma.CalculationUncheckedCreateWithoutUserInput> | Prisma.CalculationCreateWithoutUserInput[] | Prisma.CalculationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CalculationCreateOrConnectWithoutUserInput | Prisma.CalculationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CalculationUpsertWithWhereUniqueWithoutUserInput | Prisma.CalculationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CalculationCreateManyUserInputEnvelope
  set?: Prisma.CalculationWhereUniqueInput | Prisma.CalculationWhereUniqueInput[]
  disconnect?: Prisma.CalculationWhereUniqueInput | Prisma.CalculationWhereUniqueInput[]
  delete?: Prisma.CalculationWhereUniqueInput | Prisma.CalculationWhereUniqueInput[]
  connect?: Prisma.CalculationWhereUniqueInput | Prisma.CalculationWhereUniqueInput[]
  update?: Prisma.CalculationUpdateWithWhereUniqueWithoutUserInput | Prisma.CalculationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CalculationUpdateManyWithWhereWithoutUserInput | Prisma.CalculationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CalculationScalarWhereInput | Prisma.CalculationScalarWhereInput[]
}

export type CalculationCreateWithoutUserInput = {
  id?: string
  calculationType: string
  inputData: string
  result: string
  createdAt?: Date | string
}

export type CalculationUncheckedCreateWithoutUserInput = {
  id?: string
  calculationType: string
  inputData: string
  result: string
  createdAt?: Date | string
}

export type CalculationCreateOrConnectWithoutUserInput = {
  where: Prisma.CalculationWhereUniqueInput
  create: Prisma.XOR<Prisma.CalculationCreateWithoutUserInput, Prisma.CalculationUncheckedCreateWithoutUserInput>
}

export type CalculationCreateManyUserInputEnvelope = {
  data: Prisma.CalculationCreateManyUserInput | Prisma.CalculationCreateManyUserInput[]
}

export type CalculationUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CalculationWhereUniqueInput
  update: Prisma.XOR<Prisma.CalculationUpdateWithoutUserInput, Prisma.CalculationUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CalculationCreateWithoutUserInput, Prisma.CalculationUncheckedCreateWithoutUserInput>
}

export type CalculationUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CalculationWhereUniqueInput
  data: Prisma.XOR<Prisma.CalculationUpdateWithoutUserInput, Prisma.CalculationUncheckedUpdateWithoutUserInput>
}

export type CalculationUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CalculationScalarWhereInput
  data: Prisma.XOR<Prisma.CalculationUpdateManyMutationInput, Prisma.CalculationUncheckedUpdateManyWithoutUserInput>
}

export type CalculationScalarWhereInput = {
  AND?: Prisma.CalculationScalarWhereInput | Prisma.CalculationScalarWhereInput[]
  OR?: Prisma.CalculationScalarWhereInput[]
  NOT?: Prisma.CalculationScalarWhereInput | Prisma.CalculationScalarWhereInput[]
  id?: Prisma.StringFilter<"Calculation"> | string
  userId?: Prisma.StringFilter<"Calculation"> | string
  calculationType?: Prisma.StringFilter<"Calculation"> | string
  inputData?: Prisma.StringFilter<"Calculation"> | string
  result?: Prisma.StringFilter<"Calculation"> | string
  createdAt?: Prisma.DateTimeFilter<"Calculation"> | Date | string
}

export type CalculationCreateManyUserInput = {
  id?: string
  calculationType: string
  inputData: string
  result: string
  createdAt?: Date | string
}

export type CalculationUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calculationType?: Prisma.StringFieldUpdateOperationsInput | string
  inputData?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CalculationUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calculationType?: Prisma.StringFieldUpdateOperationsInput | string
  inputData?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CalculationUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calculationType?: Prisma.StringFieldUpdateOperationsInput | string
  inputData?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CalculationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  calculationType?: boolean
  inputData?: boolean
  result?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["calculation"]>

export type CalculationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  calculationType?: boolean
  inputData?: boolean
  result?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["calculation"]>

export type CalculationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  calculationType?: boolean
  inputData?: boolean
  result?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["calculation"]>

export type CalculationSelectScalar = {
  id?: boolean
  userId?: boolean
  calculationType?: boolean
  inputData?: boolean
  result?: boolean
  createdAt?: boolean
}

export type CalculationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "calculationType" | "inputData" | "result" | "createdAt", ExtArgs["result"]["calculation"]>
export type CalculationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CalculationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CalculationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CalculationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Calculation"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    calculationType: string
    inputData: string
    result: string
    createdAt: Date
  }, ExtArgs["result"]["calculation"]>
  composites: {}
}

export type CalculationGetPayload<S extends boolean | null | undefined | CalculationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CalculationPayload, S>

export type CalculationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CalculationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CalculationCountAggregateInputType | true
  }

export interface CalculationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Calculation'], meta: { name: 'Calculation' } }
  /**
   * Find zero or one Calculation that matches the filter.
   * @param {CalculationFindUniqueArgs} args - Arguments to find a Calculation
   * @example
   * // Get one Calculation
   * const calculation = await prisma.calculation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CalculationFindUniqueArgs>(args: Prisma.SelectSubset<T, CalculationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CalculationClient<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Calculation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CalculationFindUniqueOrThrowArgs} args - Arguments to find a Calculation
   * @example
   * // Get one Calculation
   * const calculation = await prisma.calculation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CalculationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CalculationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CalculationClient<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Calculation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalculationFindFirstArgs} args - Arguments to find a Calculation
   * @example
   * // Get one Calculation
   * const calculation = await prisma.calculation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CalculationFindFirstArgs>(args?: Prisma.SelectSubset<T, CalculationFindFirstArgs<ExtArgs>>): Prisma.Prisma__CalculationClient<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Calculation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalculationFindFirstOrThrowArgs} args - Arguments to find a Calculation
   * @example
   * // Get one Calculation
   * const calculation = await prisma.calculation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CalculationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CalculationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CalculationClient<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Calculations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalculationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Calculations
   * const calculations = await prisma.calculation.findMany()
   * 
   * // Get first 10 Calculations
   * const calculations = await prisma.calculation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const calculationWithIdOnly = await prisma.calculation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CalculationFindManyArgs>(args?: Prisma.SelectSubset<T, CalculationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Calculation.
   * @param {CalculationCreateArgs} args - Arguments to create a Calculation.
   * @example
   * // Create one Calculation
   * const Calculation = await prisma.calculation.create({
   *   data: {
   *     // ... data to create a Calculation
   *   }
   * })
   * 
   */
  create<T extends CalculationCreateArgs>(args: Prisma.SelectSubset<T, CalculationCreateArgs<ExtArgs>>): Prisma.Prisma__CalculationClient<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Calculations.
   * @param {CalculationCreateManyArgs} args - Arguments to create many Calculations.
   * @example
   * // Create many Calculations
   * const calculation = await prisma.calculation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CalculationCreateManyArgs>(args?: Prisma.SelectSubset<T, CalculationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Calculations and returns the data saved in the database.
   * @param {CalculationCreateManyAndReturnArgs} args - Arguments to create many Calculations.
   * @example
   * // Create many Calculations
   * const calculation = await prisma.calculation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Calculations and only return the `id`
   * const calculationWithIdOnly = await prisma.calculation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CalculationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CalculationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Calculation.
   * @param {CalculationDeleteArgs} args - Arguments to delete one Calculation.
   * @example
   * // Delete one Calculation
   * const Calculation = await prisma.calculation.delete({
   *   where: {
   *     // ... filter to delete one Calculation
   *   }
   * })
   * 
   */
  delete<T extends CalculationDeleteArgs>(args: Prisma.SelectSubset<T, CalculationDeleteArgs<ExtArgs>>): Prisma.Prisma__CalculationClient<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Calculation.
   * @param {CalculationUpdateArgs} args - Arguments to update one Calculation.
   * @example
   * // Update one Calculation
   * const calculation = await prisma.calculation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CalculationUpdateArgs>(args: Prisma.SelectSubset<T, CalculationUpdateArgs<ExtArgs>>): Prisma.Prisma__CalculationClient<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Calculations.
   * @param {CalculationDeleteManyArgs} args - Arguments to filter Calculations to delete.
   * @example
   * // Delete a few Calculations
   * const { count } = await prisma.calculation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CalculationDeleteManyArgs>(args?: Prisma.SelectSubset<T, CalculationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Calculations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalculationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Calculations
   * const calculation = await prisma.calculation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CalculationUpdateManyArgs>(args: Prisma.SelectSubset<T, CalculationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Calculations and returns the data updated in the database.
   * @param {CalculationUpdateManyAndReturnArgs} args - Arguments to update many Calculations.
   * @example
   * // Update many Calculations
   * const calculation = await prisma.calculation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Calculations and only return the `id`
   * const calculationWithIdOnly = await prisma.calculation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CalculationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CalculationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Calculation.
   * @param {CalculationUpsertArgs} args - Arguments to update or create a Calculation.
   * @example
   * // Update or create a Calculation
   * const calculation = await prisma.calculation.upsert({
   *   create: {
   *     // ... data to create a Calculation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Calculation we want to update
   *   }
   * })
   */
  upsert<T extends CalculationUpsertArgs>(args: Prisma.SelectSubset<T, CalculationUpsertArgs<ExtArgs>>): Prisma.Prisma__CalculationClient<runtime.Types.Result.GetResult<Prisma.$CalculationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Calculations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalculationCountArgs} args - Arguments to filter Calculations to count.
   * @example
   * // Count the number of Calculations
   * const count = await prisma.calculation.count({
   *   where: {
   *     // ... the filter for the Calculations we want to count
   *   }
   * })
  **/
  count<T extends CalculationCountArgs>(
    args?: Prisma.Subset<T, CalculationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CalculationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Calculation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalculationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CalculationAggregateArgs>(args: Prisma.Subset<T, CalculationAggregateArgs>): Prisma.PrismaPromise<GetCalculationAggregateType<T>>

  /**
   * Group by Calculation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalculationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CalculationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CalculationGroupByArgs['orderBy'] }
      : { orderBy?: CalculationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CalculationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCalculationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Calculation model
 */
readonly fields: CalculationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Calculation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CalculationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Calculation model
 */
export interface CalculationFieldRefs {
  readonly id: Prisma.FieldRef<"Calculation", 'String'>
  readonly userId: Prisma.FieldRef<"Calculation", 'String'>
  readonly calculationType: Prisma.FieldRef<"Calculation", 'String'>
  readonly inputData: Prisma.FieldRef<"Calculation", 'String'>
  readonly result: Prisma.FieldRef<"Calculation", 'String'>
  readonly createdAt: Prisma.FieldRef<"Calculation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Calculation findUnique
 */
export type CalculationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationInclude<ExtArgs> | null
  /**
   * Filter, which Calculation to fetch.
   */
  where: Prisma.CalculationWhereUniqueInput
}

/**
 * Calculation findUniqueOrThrow
 */
export type CalculationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationInclude<ExtArgs> | null
  /**
   * Filter, which Calculation to fetch.
   */
  where: Prisma.CalculationWhereUniqueInput
}

/**
 * Calculation findFirst
 */
export type CalculationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationInclude<ExtArgs> | null
  /**
   * Filter, which Calculation to fetch.
   */
  where?: Prisma.CalculationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Calculations to fetch.
   */
  orderBy?: Prisma.CalculationOrderByWithRelationInput | Prisma.CalculationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Calculations.
   */
  cursor?: Prisma.CalculationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Calculations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Calculations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Calculations.
   */
  distinct?: Prisma.CalculationScalarFieldEnum | Prisma.CalculationScalarFieldEnum[]
}

/**
 * Calculation findFirstOrThrow
 */
export type CalculationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationInclude<ExtArgs> | null
  /**
   * Filter, which Calculation to fetch.
   */
  where?: Prisma.CalculationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Calculations to fetch.
   */
  orderBy?: Prisma.CalculationOrderByWithRelationInput | Prisma.CalculationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Calculations.
   */
  cursor?: Prisma.CalculationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Calculations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Calculations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Calculations.
   */
  distinct?: Prisma.CalculationScalarFieldEnum | Prisma.CalculationScalarFieldEnum[]
}

/**
 * Calculation findMany
 */
export type CalculationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationInclude<ExtArgs> | null
  /**
   * Filter, which Calculations to fetch.
   */
  where?: Prisma.CalculationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Calculations to fetch.
   */
  orderBy?: Prisma.CalculationOrderByWithRelationInput | Prisma.CalculationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Calculations.
   */
  cursor?: Prisma.CalculationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Calculations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Calculations.
   */
  skip?: number
  distinct?: Prisma.CalculationScalarFieldEnum | Prisma.CalculationScalarFieldEnum[]
}

/**
 * Calculation create
 */
export type CalculationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationInclude<ExtArgs> | null
  /**
   * The data needed to create a Calculation.
   */
  data: Prisma.XOR<Prisma.CalculationCreateInput, Prisma.CalculationUncheckedCreateInput>
}

/**
 * Calculation createMany
 */
export type CalculationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Calculations.
   */
  data: Prisma.CalculationCreateManyInput | Prisma.CalculationCreateManyInput[]
}

/**
 * Calculation createManyAndReturn
 */
export type CalculationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * The data used to create many Calculations.
   */
  data: Prisma.CalculationCreateManyInput | Prisma.CalculationCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Calculation update
 */
export type CalculationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationInclude<ExtArgs> | null
  /**
   * The data needed to update a Calculation.
   */
  data: Prisma.XOR<Prisma.CalculationUpdateInput, Prisma.CalculationUncheckedUpdateInput>
  /**
   * Choose, which Calculation to update.
   */
  where: Prisma.CalculationWhereUniqueInput
}

/**
 * Calculation updateMany
 */
export type CalculationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Calculations.
   */
  data: Prisma.XOR<Prisma.CalculationUpdateManyMutationInput, Prisma.CalculationUncheckedUpdateManyInput>
  /**
   * Filter which Calculations to update
   */
  where?: Prisma.CalculationWhereInput
  /**
   * Limit how many Calculations to update.
   */
  limit?: number
}

/**
 * Calculation updateManyAndReturn
 */
export type CalculationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * The data used to update Calculations.
   */
  data: Prisma.XOR<Prisma.CalculationUpdateManyMutationInput, Prisma.CalculationUncheckedUpdateManyInput>
  /**
   * Filter which Calculations to update
   */
  where?: Prisma.CalculationWhereInput
  /**
   * Limit how many Calculations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Calculation upsert
 */
export type CalculationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationInclude<ExtArgs> | null
  /**
   * The filter to search for the Calculation to update in case it exists.
   */
  where: Prisma.CalculationWhereUniqueInput
  /**
   * In case the Calculation found by the `where` argument doesn't exist, create a new Calculation with this data.
   */
  create: Prisma.XOR<Prisma.CalculationCreateInput, Prisma.CalculationUncheckedCreateInput>
  /**
   * In case the Calculation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CalculationUpdateInput, Prisma.CalculationUncheckedUpdateInput>
}

/**
 * Calculation delete
 */
export type CalculationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationInclude<ExtArgs> | null
  /**
   * Filter which Calculation to delete.
   */
  where: Prisma.CalculationWhereUniqueInput
}

/**
 * Calculation deleteMany
 */
export type CalculationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Calculations to delete
   */
  where?: Prisma.CalculationWhereInput
  /**
   * Limit how many Calculations to delete.
   */
  limit?: number
}

/**
 * Calculation without action
 */
export type CalculationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Calculation
   */
  select?: Prisma.CalculationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Calculation
   */
  omit?: Prisma.CalculationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalculationInclude<ExtArgs> | null
}
