
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Checklist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Checklist
 * 
 */
export type ChecklistModel = runtime.Types.Result.DefaultSelection<Prisma.$ChecklistPayload>

export type AggregateChecklist = {
  _count: ChecklistCountAggregateOutputType | null
  _min: ChecklistMinAggregateOutputType | null
  _max: ChecklistMaxAggregateOutputType | null
}

export type ChecklistMinAggregateOutputType = {
  id: string | null
  userId: string | null
  type: string | null
  title: string | null
  description: string | null
  category: string | null
  isCompleted: boolean | null
  dueDate: Date | null
  priority: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ChecklistMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  type: string | null
  title: string | null
  description: string | null
  category: string | null
  isCompleted: boolean | null
  dueDate: Date | null
  priority: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ChecklistCountAggregateOutputType = {
  id: number
  userId: number
  type: number
  title: number
  description: number
  category: number
  isCompleted: number
  dueDate: number
  priority: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ChecklistMinAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  title?: true
  description?: true
  category?: true
  isCompleted?: true
  dueDate?: true
  priority?: true
  createdAt?: true
  updatedAt?: true
}

export type ChecklistMaxAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  title?: true
  description?: true
  category?: true
  isCompleted?: true
  dueDate?: true
  priority?: true
  createdAt?: true
  updatedAt?: true
}

export type ChecklistCountAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  title?: true
  description?: true
  category?: true
  isCompleted?: true
  dueDate?: true
  priority?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ChecklistAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Checklist to aggregate.
   */
  where?: Prisma.ChecklistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checklists to fetch.
   */
  orderBy?: Prisma.ChecklistOrderByWithRelationInput | Prisma.ChecklistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ChecklistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checklists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checklists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Checklists
  **/
  _count?: true | ChecklistCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ChecklistMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ChecklistMaxAggregateInputType
}

export type GetChecklistAggregateType<T extends ChecklistAggregateArgs> = {
      [P in keyof T & keyof AggregateChecklist]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateChecklist[P]>
    : Prisma.GetScalarType<T[P], AggregateChecklist[P]>
}




export type ChecklistGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChecklistWhereInput
  orderBy?: Prisma.ChecklistOrderByWithAggregationInput | Prisma.ChecklistOrderByWithAggregationInput[]
  by: Prisma.ChecklistScalarFieldEnum[] | Prisma.ChecklistScalarFieldEnum
  having?: Prisma.ChecklistScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ChecklistCountAggregateInputType | true
  _min?: ChecklistMinAggregateInputType
  _max?: ChecklistMaxAggregateInputType
}

export type ChecklistGroupByOutputType = {
  id: string
  userId: string
  type: string
  title: string
  description: string | null
  category: string | null
  isCompleted: boolean
  dueDate: Date | null
  priority: string | null
  createdAt: Date
  updatedAt: Date
  _count: ChecklistCountAggregateOutputType | null
  _min: ChecklistMinAggregateOutputType | null
  _max: ChecklistMaxAggregateOutputType | null
}

type GetChecklistGroupByPayload<T extends ChecklistGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ChecklistGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ChecklistGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ChecklistGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ChecklistGroupByOutputType[P]>
      }
    >
  >



export type ChecklistWhereInput = {
  AND?: Prisma.ChecklistWhereInput | Prisma.ChecklistWhereInput[]
  OR?: Prisma.ChecklistWhereInput[]
  NOT?: Prisma.ChecklistWhereInput | Prisma.ChecklistWhereInput[]
  id?: Prisma.StringFilter<"Checklist"> | string
  userId?: Prisma.StringFilter<"Checklist"> | string
  type?: Prisma.StringFilter<"Checklist"> | string
  title?: Prisma.StringFilter<"Checklist"> | string
  description?: Prisma.StringNullableFilter<"Checklist"> | string | null
  category?: Prisma.StringNullableFilter<"Checklist"> | string | null
  isCompleted?: Prisma.BoolFilter<"Checklist"> | boolean
  dueDate?: Prisma.DateTimeNullableFilter<"Checklist"> | Date | string | null
  priority?: Prisma.StringNullableFilter<"Checklist"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Checklist"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Checklist"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ChecklistOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  isCompleted?: Prisma.SortOrder
  dueDate?: Prisma.SortOrderInput | Prisma.SortOrder
  priority?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type ChecklistWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ChecklistWhereInput | Prisma.ChecklistWhereInput[]
  OR?: Prisma.ChecklistWhereInput[]
  NOT?: Prisma.ChecklistWhereInput | Prisma.ChecklistWhereInput[]
  userId?: Prisma.StringFilter<"Checklist"> | string
  type?: Prisma.StringFilter<"Checklist"> | string
  title?: Prisma.StringFilter<"Checklist"> | string
  description?: Prisma.StringNullableFilter<"Checklist"> | string | null
  category?: Prisma.StringNullableFilter<"Checklist"> | string | null
  isCompleted?: Prisma.BoolFilter<"Checklist"> | boolean
  dueDate?: Prisma.DateTimeNullableFilter<"Checklist"> | Date | string | null
  priority?: Prisma.StringNullableFilter<"Checklist"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Checklist"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Checklist"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type ChecklistOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  isCompleted?: Prisma.SortOrder
  dueDate?: Prisma.SortOrderInput | Prisma.SortOrder
  priority?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ChecklistCountOrderByAggregateInput
  _max?: Prisma.ChecklistMaxOrderByAggregateInput
  _min?: Prisma.ChecklistMinOrderByAggregateInput
}

export type ChecklistScalarWhereWithAggregatesInput = {
  AND?: Prisma.ChecklistScalarWhereWithAggregatesInput | Prisma.ChecklistScalarWhereWithAggregatesInput[]
  OR?: Prisma.ChecklistScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ChecklistScalarWhereWithAggregatesInput | Prisma.ChecklistScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Checklist"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Checklist"> | string
  type?: Prisma.StringWithAggregatesFilter<"Checklist"> | string
  title?: Prisma.StringWithAggregatesFilter<"Checklist"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Checklist"> | string | null
  category?: Prisma.StringNullableWithAggregatesFilter<"Checklist"> | string | null
  isCompleted?: Prisma.BoolWithAggregatesFilter<"Checklist"> | boolean
  dueDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Checklist"> | Date | string | null
  priority?: Prisma.StringNullableWithAggregatesFilter<"Checklist"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Checklist"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Checklist"> | Date | string
}

export type ChecklistCreateInput = {
  id?: string
  type: string
  title: string
  description?: string | null
  category?: string | null
  isCompleted?: boolean
  dueDate?: Date | string | null
  priority?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutChecklistsInput
}

export type ChecklistUncheckedCreateInput = {
  id?: string
  userId: string
  type: string
  title: string
  description?: string | null
  category?: string | null
  isCompleted?: boolean
  dueDate?: Date | string | null
  priority?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChecklistUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  priority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutChecklistsNestedInput
}

export type ChecklistUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  priority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChecklistCreateManyInput = {
  id?: string
  userId: string
  type: string
  title: string
  description?: string | null
  category?: string | null
  isCompleted?: boolean
  dueDate?: Date | string | null
  priority?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChecklistUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  priority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChecklistUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  priority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChecklistListRelationFilter = {
  every?: Prisma.ChecklistWhereInput
  some?: Prisma.ChecklistWhereInput
  none?: Prisma.ChecklistWhereInput
}

export type ChecklistOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ChecklistCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isCompleted?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChecklistMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isCompleted?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChecklistMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isCompleted?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChecklistCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ChecklistCreateWithoutUserInput, Prisma.ChecklistUncheckedCreateWithoutUserInput> | Prisma.ChecklistCreateWithoutUserInput[] | Prisma.ChecklistUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ChecklistCreateOrConnectWithoutUserInput | Prisma.ChecklistCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ChecklistCreateManyUserInputEnvelope
  connect?: Prisma.ChecklistWhereUniqueInput | Prisma.ChecklistWhereUniqueInput[]
}

export type ChecklistUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ChecklistCreateWithoutUserInput, Prisma.ChecklistUncheckedCreateWithoutUserInput> | Prisma.ChecklistCreateWithoutUserInput[] | Prisma.ChecklistUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ChecklistCreateOrConnectWithoutUserInput | Prisma.ChecklistCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ChecklistCreateManyUserInputEnvelope
  connect?: Prisma.ChecklistWhereUniqueInput | Prisma.ChecklistWhereUniqueInput[]
}

export type ChecklistUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ChecklistCreateWithoutUserInput, Prisma.ChecklistUncheckedCreateWithoutUserInput> | Prisma.ChecklistCreateWithoutUserInput[] | Prisma.ChecklistUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ChecklistCreateOrConnectWithoutUserInput | Prisma.ChecklistCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ChecklistUpsertWithWhereUniqueWithoutUserInput | Prisma.ChecklistUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ChecklistCreateManyUserInputEnvelope
  set?: Prisma.ChecklistWhereUniqueInput | Prisma.ChecklistWhereUniqueInput[]
  disconnect?: Prisma.ChecklistWhereUniqueInput | Prisma.ChecklistWhereUniqueInput[]
  delete?: Prisma.ChecklistWhereUniqueInput | Prisma.ChecklistWhereUniqueInput[]
  connect?: Prisma.ChecklistWhereUniqueInput | Prisma.ChecklistWhereUniqueInput[]
  update?: Prisma.ChecklistUpdateWithWhereUniqueWithoutUserInput | Prisma.ChecklistUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ChecklistUpdateManyWithWhereWithoutUserInput | Prisma.ChecklistUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ChecklistScalarWhereInput | Prisma.ChecklistScalarWhereInput[]
}

export type ChecklistUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ChecklistCreateWithoutUserInput, Prisma.ChecklistUncheckedCreateWithoutUserInput> | Prisma.ChecklistCreateWithoutUserInput[] | Prisma.ChecklistUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ChecklistCreateOrConnectWithoutUserInput | Prisma.ChecklistCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ChecklistUpsertWithWhereUniqueWithoutUserInput | Prisma.ChecklistUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ChecklistCreateManyUserInputEnvelope
  set?: Prisma.ChecklistWhereUniqueInput | Prisma.ChecklistWhereUniqueInput[]
  disconnect?: Prisma.ChecklistWhereUniqueInput | Prisma.ChecklistWhereUniqueInput[]
  delete?: Prisma.ChecklistWhereUniqueInput | Prisma.ChecklistWhereUniqueInput[]
  connect?: Prisma.ChecklistWhereUniqueInput | Prisma.ChecklistWhereUniqueInput[]
  update?: Prisma.ChecklistUpdateWithWhereUniqueWithoutUserInput | Prisma.ChecklistUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ChecklistUpdateManyWithWhereWithoutUserInput | Prisma.ChecklistUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ChecklistScalarWhereInput | Prisma.ChecklistScalarWhereInput[]
}

export type ChecklistCreateWithoutUserInput = {
  id?: string
  type: string
  title: string
  description?: string | null
  category?: string | null
  isCompleted?: boolean
  dueDate?: Date | string | null
  priority?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChecklistUncheckedCreateWithoutUserInput = {
  id?: string
  type: string
  title: string
  description?: string | null
  category?: string | null
  isCompleted?: boolean
  dueDate?: Date | string | null
  priority?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChecklistCreateOrConnectWithoutUserInput = {
  where: Prisma.ChecklistWhereUniqueInput
  create: Prisma.XOR<Prisma.ChecklistCreateWithoutUserInput, Prisma.ChecklistUncheckedCreateWithoutUserInput>
}

export type ChecklistCreateManyUserInputEnvelope = {
  data: Prisma.ChecklistCreateManyUserInput | Prisma.ChecklistCreateManyUserInput[]
}

export type ChecklistUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ChecklistWhereUniqueInput
  update: Prisma.XOR<Prisma.ChecklistUpdateWithoutUserInput, Prisma.ChecklistUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ChecklistCreateWithoutUserInput, Prisma.ChecklistUncheckedCreateWithoutUserInput>
}

export type ChecklistUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ChecklistWhereUniqueInput
  data: Prisma.XOR<Prisma.ChecklistUpdateWithoutUserInput, Prisma.ChecklistUncheckedUpdateWithoutUserInput>
}

export type ChecklistUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ChecklistScalarWhereInput
  data: Prisma.XOR<Prisma.ChecklistUpdateManyMutationInput, Prisma.ChecklistUncheckedUpdateManyWithoutUserInput>
}

export type ChecklistScalarWhereInput = {
  AND?: Prisma.ChecklistScalarWhereInput | Prisma.ChecklistScalarWhereInput[]
  OR?: Prisma.ChecklistScalarWhereInput[]
  NOT?: Prisma.ChecklistScalarWhereInput | Prisma.ChecklistScalarWhereInput[]
  id?: Prisma.StringFilter<"Checklist"> | string
  userId?: Prisma.StringFilter<"Checklist"> | string
  type?: Prisma.StringFilter<"Checklist"> | string
  title?: Prisma.StringFilter<"Checklist"> | string
  description?: Prisma.StringNullableFilter<"Checklist"> | string | null
  category?: Prisma.StringNullableFilter<"Checklist"> | string | null
  isCompleted?: Prisma.BoolFilter<"Checklist"> | boolean
  dueDate?: Prisma.DateTimeNullableFilter<"Checklist"> | Date | string | null
  priority?: Prisma.StringNullableFilter<"Checklist"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Checklist"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Checklist"> | Date | string
}

export type ChecklistCreateManyUserInput = {
  id?: string
  type: string
  title: string
  description?: string | null
  category?: string | null
  isCompleted?: boolean
  dueDate?: Date | string | null
  priority?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChecklistUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  priority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChecklistUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  priority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChecklistUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  priority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ChecklistSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  isCompleted?: boolean
  dueDate?: boolean
  priority?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checklist"]>

export type ChecklistSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  isCompleted?: boolean
  dueDate?: boolean
  priority?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checklist"]>

export type ChecklistSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  isCompleted?: boolean
  dueDate?: boolean
  priority?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checklist"]>

export type ChecklistSelectScalar = {
  id?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  isCompleted?: boolean
  dueDate?: boolean
  priority?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ChecklistOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "type" | "title" | "description" | "category" | "isCompleted" | "dueDate" | "priority" | "createdAt" | "updatedAt", ExtArgs["result"]["checklist"]>
export type ChecklistInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ChecklistIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ChecklistIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ChecklistPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Checklist"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    type: string
    title: string
    description: string | null
    category: string | null
    isCompleted: boolean
    dueDate: Date | null
    priority: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["checklist"]>
  composites: {}
}

export type ChecklistGetPayload<S extends boolean | null | undefined | ChecklistDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ChecklistPayload, S>

export type ChecklistCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ChecklistFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ChecklistCountAggregateInputType | true
  }

export interface ChecklistDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Checklist'], meta: { name: 'Checklist' } }
  /**
   * Find zero or one Checklist that matches the filter.
   * @param {ChecklistFindUniqueArgs} args - Arguments to find a Checklist
   * @example
   * // Get one Checklist
   * const checklist = await prisma.checklist.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ChecklistFindUniqueArgs>(args: Prisma.SelectSubset<T, ChecklistFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ChecklistClient<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Checklist that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ChecklistFindUniqueOrThrowArgs} args - Arguments to find a Checklist
   * @example
   * // Get one Checklist
   * const checklist = await prisma.checklist.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ChecklistFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ChecklistFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChecklistClient<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Checklist that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChecklistFindFirstArgs} args - Arguments to find a Checklist
   * @example
   * // Get one Checklist
   * const checklist = await prisma.checklist.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ChecklistFindFirstArgs>(args?: Prisma.SelectSubset<T, ChecklistFindFirstArgs<ExtArgs>>): Prisma.Prisma__ChecklistClient<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Checklist that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChecklistFindFirstOrThrowArgs} args - Arguments to find a Checklist
   * @example
   * // Get one Checklist
   * const checklist = await prisma.checklist.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ChecklistFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ChecklistFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChecklistClient<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Checklists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChecklistFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Checklists
   * const checklists = await prisma.checklist.findMany()
   * 
   * // Get first 10 Checklists
   * const checklists = await prisma.checklist.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const checklistWithIdOnly = await prisma.checklist.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ChecklistFindManyArgs>(args?: Prisma.SelectSubset<T, ChecklistFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Checklist.
   * @param {ChecklistCreateArgs} args - Arguments to create a Checklist.
   * @example
   * // Create one Checklist
   * const Checklist = await prisma.checklist.create({
   *   data: {
   *     // ... data to create a Checklist
   *   }
   * })
   * 
   */
  create<T extends ChecklistCreateArgs>(args: Prisma.SelectSubset<T, ChecklistCreateArgs<ExtArgs>>): Prisma.Prisma__ChecklistClient<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Checklists.
   * @param {ChecklistCreateManyArgs} args - Arguments to create many Checklists.
   * @example
   * // Create many Checklists
   * const checklist = await prisma.checklist.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ChecklistCreateManyArgs>(args?: Prisma.SelectSubset<T, ChecklistCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Checklists and returns the data saved in the database.
   * @param {ChecklistCreateManyAndReturnArgs} args - Arguments to create many Checklists.
   * @example
   * // Create many Checklists
   * const checklist = await prisma.checklist.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Checklists and only return the `id`
   * const checklistWithIdOnly = await prisma.checklist.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ChecklistCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ChecklistCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Checklist.
   * @param {ChecklistDeleteArgs} args - Arguments to delete one Checklist.
   * @example
   * // Delete one Checklist
   * const Checklist = await prisma.checklist.delete({
   *   where: {
   *     // ... filter to delete one Checklist
   *   }
   * })
   * 
   */
  delete<T extends ChecklistDeleteArgs>(args: Prisma.SelectSubset<T, ChecklistDeleteArgs<ExtArgs>>): Prisma.Prisma__ChecklistClient<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Checklist.
   * @param {ChecklistUpdateArgs} args - Arguments to update one Checklist.
   * @example
   * // Update one Checklist
   * const checklist = await prisma.checklist.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ChecklistUpdateArgs>(args: Prisma.SelectSubset<T, ChecklistUpdateArgs<ExtArgs>>): Prisma.Prisma__ChecklistClient<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Checklists.
   * @param {ChecklistDeleteManyArgs} args - Arguments to filter Checklists to delete.
   * @example
   * // Delete a few Checklists
   * const { count } = await prisma.checklist.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ChecklistDeleteManyArgs>(args?: Prisma.SelectSubset<T, ChecklistDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Checklists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChecklistUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Checklists
   * const checklist = await prisma.checklist.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ChecklistUpdateManyArgs>(args: Prisma.SelectSubset<T, ChecklistUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Checklists and returns the data updated in the database.
   * @param {ChecklistUpdateManyAndReturnArgs} args - Arguments to update many Checklists.
   * @example
   * // Update many Checklists
   * const checklist = await prisma.checklist.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Checklists and only return the `id`
   * const checklistWithIdOnly = await prisma.checklist.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ChecklistUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ChecklistUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Checklist.
   * @param {ChecklistUpsertArgs} args - Arguments to update or create a Checklist.
   * @example
   * // Update or create a Checklist
   * const checklist = await prisma.checklist.upsert({
   *   create: {
   *     // ... data to create a Checklist
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Checklist we want to update
   *   }
   * })
   */
  upsert<T extends ChecklistUpsertArgs>(args: Prisma.SelectSubset<T, ChecklistUpsertArgs<ExtArgs>>): Prisma.Prisma__ChecklistClient<runtime.Types.Result.GetResult<Prisma.$ChecklistPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Checklists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChecklistCountArgs} args - Arguments to filter Checklists to count.
   * @example
   * // Count the number of Checklists
   * const count = await prisma.checklist.count({
   *   where: {
   *     // ... the filter for the Checklists we want to count
   *   }
   * })
  **/
  count<T extends ChecklistCountArgs>(
    args?: Prisma.Subset<T, ChecklistCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ChecklistCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Checklist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChecklistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ChecklistAggregateArgs>(args: Prisma.Subset<T, ChecklistAggregateArgs>): Prisma.PrismaPromise<GetChecklistAggregateType<T>>

  /**
   * Group by Checklist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChecklistGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ChecklistGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ChecklistGroupByArgs['orderBy'] }
      : { orderBy?: ChecklistGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ChecklistGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetChecklistGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Checklist model
 */
readonly fields: ChecklistFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Checklist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ChecklistClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Checklist model
 */
export interface ChecklistFieldRefs {
  readonly id: Prisma.FieldRef<"Checklist", 'String'>
  readonly userId: Prisma.FieldRef<"Checklist", 'String'>
  readonly type: Prisma.FieldRef<"Checklist", 'String'>
  readonly title: Prisma.FieldRef<"Checklist", 'String'>
  readonly description: Prisma.FieldRef<"Checklist", 'String'>
  readonly category: Prisma.FieldRef<"Checklist", 'String'>
  readonly isCompleted: Prisma.FieldRef<"Checklist", 'Boolean'>
  readonly dueDate: Prisma.FieldRef<"Checklist", 'DateTime'>
  readonly priority: Prisma.FieldRef<"Checklist", 'String'>
  readonly createdAt: Prisma.FieldRef<"Checklist", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Checklist", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Checklist findUnique
 */
export type ChecklistFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistInclude<ExtArgs> | null
  /**
   * Filter, which Checklist to fetch.
   */
  where: Prisma.ChecklistWhereUniqueInput
}

/**
 * Checklist findUniqueOrThrow
 */
export type ChecklistFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistInclude<ExtArgs> | null
  /**
   * Filter, which Checklist to fetch.
   */
  where: Prisma.ChecklistWhereUniqueInput
}

/**
 * Checklist findFirst
 */
export type ChecklistFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistInclude<ExtArgs> | null
  /**
   * Filter, which Checklist to fetch.
   */
  where?: Prisma.ChecklistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checklists to fetch.
   */
  orderBy?: Prisma.ChecklistOrderByWithRelationInput | Prisma.ChecklistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Checklists.
   */
  cursor?: Prisma.ChecklistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checklists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checklists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Checklists.
   */
  distinct?: Prisma.ChecklistScalarFieldEnum | Prisma.ChecklistScalarFieldEnum[]
}

/**
 * Checklist findFirstOrThrow
 */
export type ChecklistFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistInclude<ExtArgs> | null
  /**
   * Filter, which Checklist to fetch.
   */
  where?: Prisma.ChecklistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checklists to fetch.
   */
  orderBy?: Prisma.ChecklistOrderByWithRelationInput | Prisma.ChecklistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Checklists.
   */
  cursor?: Prisma.ChecklistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checklists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checklists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Checklists.
   */
  distinct?: Prisma.ChecklistScalarFieldEnum | Prisma.ChecklistScalarFieldEnum[]
}

/**
 * Checklist findMany
 */
export type ChecklistFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistInclude<ExtArgs> | null
  /**
   * Filter, which Checklists to fetch.
   */
  where?: Prisma.ChecklistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checklists to fetch.
   */
  orderBy?: Prisma.ChecklistOrderByWithRelationInput | Prisma.ChecklistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Checklists.
   */
  cursor?: Prisma.ChecklistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checklists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checklists.
   */
  skip?: number
  distinct?: Prisma.ChecklistScalarFieldEnum | Prisma.ChecklistScalarFieldEnum[]
}

/**
 * Checklist create
 */
export type ChecklistCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistInclude<ExtArgs> | null
  /**
   * The data needed to create a Checklist.
   */
  data: Prisma.XOR<Prisma.ChecklistCreateInput, Prisma.ChecklistUncheckedCreateInput>
}

/**
 * Checklist createMany
 */
export type ChecklistCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Checklists.
   */
  data: Prisma.ChecklistCreateManyInput | Prisma.ChecklistCreateManyInput[]
}

/**
 * Checklist createManyAndReturn
 */
export type ChecklistCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * The data used to create many Checklists.
   */
  data: Prisma.ChecklistCreateManyInput | Prisma.ChecklistCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Checklist update
 */
export type ChecklistUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistInclude<ExtArgs> | null
  /**
   * The data needed to update a Checklist.
   */
  data: Prisma.XOR<Prisma.ChecklistUpdateInput, Prisma.ChecklistUncheckedUpdateInput>
  /**
   * Choose, which Checklist to update.
   */
  where: Prisma.ChecklistWhereUniqueInput
}

/**
 * Checklist updateMany
 */
export type ChecklistUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Checklists.
   */
  data: Prisma.XOR<Prisma.ChecklistUpdateManyMutationInput, Prisma.ChecklistUncheckedUpdateManyInput>
  /**
   * Filter which Checklists to update
   */
  where?: Prisma.ChecklistWhereInput
  /**
   * Limit how many Checklists to update.
   */
  limit?: number
}

/**
 * Checklist updateManyAndReturn
 */
export type ChecklistUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * The data used to update Checklists.
   */
  data: Prisma.XOR<Prisma.ChecklistUpdateManyMutationInput, Prisma.ChecklistUncheckedUpdateManyInput>
  /**
   * Filter which Checklists to update
   */
  where?: Prisma.ChecklistWhereInput
  /**
   * Limit how many Checklists to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Checklist upsert
 */
export type ChecklistUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistInclude<ExtArgs> | null
  /**
   * The filter to search for the Checklist to update in case it exists.
   */
  where: Prisma.ChecklistWhereUniqueInput
  /**
   * In case the Checklist found by the `where` argument doesn't exist, create a new Checklist with this data.
   */
  create: Prisma.XOR<Prisma.ChecklistCreateInput, Prisma.ChecklistUncheckedCreateInput>
  /**
   * In case the Checklist was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ChecklistUpdateInput, Prisma.ChecklistUncheckedUpdateInput>
}

/**
 * Checklist delete
 */
export type ChecklistDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistInclude<ExtArgs> | null
  /**
   * Filter which Checklist to delete.
   */
  where: Prisma.ChecklistWhereUniqueInput
}

/**
 * Checklist deleteMany
 */
export type ChecklistDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Checklists to delete
   */
  where?: Prisma.ChecklistWhereInput
  /**
   * Limit how many Checklists to delete.
   */
  limit?: number
}

/**
 * Checklist without action
 */
export type ChecklistDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checklist
   */
  select?: Prisma.ChecklistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checklist
   */
  omit?: Prisma.ChecklistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChecklistInclude<ExtArgs> | null
}
