
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Policy` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Policy
 * 
 */
export type PolicyModel = runtime.Types.Result.DefaultSelection<Prisma.$PolicyPayload>

export type AggregatePolicy = {
  _count: PolicyCountAggregateOutputType | null
  _avg: PolicyAvgAggregateOutputType | null
  _sum: PolicySumAggregateOutputType | null
  _min: PolicyMinAggregateOutputType | null
  _max: PolicyMaxAggregateOutputType | null
}

export type PolicyAvgAggregateOutputType = {
  minChildCount: number | null
  maxChildCount: number | null
  minChildAge: number | null
  maxChildAge: number | null
  benefitAmount: number | null
}

export type PolicySumAggregateOutputType = {
  minChildCount: number | null
  maxChildCount: number | null
  minChildAge: number | null
  maxChildAge: number | null
  benefitAmount: number | null
}

export type PolicyMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  category: string | null
  targetCity: string | null
  targetDistrict: string | null
  minIncomeLevel: string | null
  maxIncomeLevel: string | null
  minChildCount: number | null
  maxChildCount: number | null
  minChildAge: number | null
  maxChildAge: number | null
  requiresDualIncome: boolean | null
  requiresMultiChild: boolean | null
  benefitAmount: number | null
  benefitType: string | null
  benefitDescription: string | null
  applicationStart: Date | null
  applicationEnd: Date | null
  applicationUrl: string | null
  requiredDocuments: string | null
  isCentralGov: boolean | null
  govLevel: string | null
  infographicUrl: string | null
  cardImageUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PolicyMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  category: string | null
  targetCity: string | null
  targetDistrict: string | null
  minIncomeLevel: string | null
  maxIncomeLevel: string | null
  minChildCount: number | null
  maxChildCount: number | null
  minChildAge: number | null
  maxChildAge: number | null
  requiresDualIncome: boolean | null
  requiresMultiChild: boolean | null
  benefitAmount: number | null
  benefitType: string | null
  benefitDescription: string | null
  applicationStart: Date | null
  applicationEnd: Date | null
  applicationUrl: string | null
  requiredDocuments: string | null
  isCentralGov: boolean | null
  govLevel: string | null
  infographicUrl: string | null
  cardImageUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PolicyCountAggregateOutputType = {
  id: number
  title: number
  description: number
  category: number
  targetCity: number
  targetDistrict: number
  minIncomeLevel: number
  maxIncomeLevel: number
  minChildCount: number
  maxChildCount: number
  minChildAge: number
  maxChildAge: number
  requiresDualIncome: number
  requiresMultiChild: number
  benefitAmount: number
  benefitType: number
  benefitDescription: number
  applicationStart: number
  applicationEnd: number
  applicationUrl: number
  requiredDocuments: number
  isCentralGov: number
  govLevel: number
  infographicUrl: number
  cardImageUrl: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PolicyAvgAggregateInputType = {
  minChildCount?: true
  maxChildCount?: true
  minChildAge?: true
  maxChildAge?: true
  benefitAmount?: true
}

export type PolicySumAggregateInputType = {
  minChildCount?: true
  maxChildCount?: true
  minChildAge?: true
  maxChildAge?: true
  benefitAmount?: true
}

export type PolicyMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  category?: true
  targetCity?: true
  targetDistrict?: true
  minIncomeLevel?: true
  maxIncomeLevel?: true
  minChildCount?: true
  maxChildCount?: true
  minChildAge?: true
  maxChildAge?: true
  requiresDualIncome?: true
  requiresMultiChild?: true
  benefitAmount?: true
  benefitType?: true
  benefitDescription?: true
  applicationStart?: true
  applicationEnd?: true
  applicationUrl?: true
  requiredDocuments?: true
  isCentralGov?: true
  govLevel?: true
  infographicUrl?: true
  cardImageUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type PolicyMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  category?: true
  targetCity?: true
  targetDistrict?: true
  minIncomeLevel?: true
  maxIncomeLevel?: true
  minChildCount?: true
  maxChildCount?: true
  minChildAge?: true
  maxChildAge?: true
  requiresDualIncome?: true
  requiresMultiChild?: true
  benefitAmount?: true
  benefitType?: true
  benefitDescription?: true
  applicationStart?: true
  applicationEnd?: true
  applicationUrl?: true
  requiredDocuments?: true
  isCentralGov?: true
  govLevel?: true
  infographicUrl?: true
  cardImageUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type PolicyCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  category?: true
  targetCity?: true
  targetDistrict?: true
  minIncomeLevel?: true
  maxIncomeLevel?: true
  minChildCount?: true
  maxChildCount?: true
  minChildAge?: true
  maxChildAge?: true
  requiresDualIncome?: true
  requiresMultiChild?: true
  benefitAmount?: true
  benefitType?: true
  benefitDescription?: true
  applicationStart?: true
  applicationEnd?: true
  applicationUrl?: true
  requiredDocuments?: true
  isCentralGov?: true
  govLevel?: true
  infographicUrl?: true
  cardImageUrl?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PolicyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Policy to aggregate.
   */
  where?: Prisma.PolicyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Policies to fetch.
   */
  orderBy?: Prisma.PolicyOrderByWithRelationInput | Prisma.PolicyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PolicyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Policies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Policies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Policies
  **/
  _count?: true | PolicyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PolicyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PolicySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PolicyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PolicyMaxAggregateInputType
}

export type GetPolicyAggregateType<T extends PolicyAggregateArgs> = {
      [P in keyof T & keyof AggregatePolicy]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePolicy[P]>
    : Prisma.GetScalarType<T[P], AggregatePolicy[P]>
}




export type PolicyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PolicyWhereInput
  orderBy?: Prisma.PolicyOrderByWithAggregationInput | Prisma.PolicyOrderByWithAggregationInput[]
  by: Prisma.PolicyScalarFieldEnum[] | Prisma.PolicyScalarFieldEnum
  having?: Prisma.PolicyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PolicyCountAggregateInputType | true
  _avg?: PolicyAvgAggregateInputType
  _sum?: PolicySumAggregateInputType
  _min?: PolicyMinAggregateInputType
  _max?: PolicyMaxAggregateInputType
}

export type PolicyGroupByOutputType = {
  id: string
  title: string
  description: string | null
  category: string
  targetCity: string | null
  targetDistrict: string | null
  minIncomeLevel: string | null
  maxIncomeLevel: string | null
  minChildCount: number | null
  maxChildCount: number | null
  minChildAge: number | null
  maxChildAge: number | null
  requiresDualIncome: boolean
  requiresMultiChild: boolean
  benefitAmount: number | null
  benefitType: string | null
  benefitDescription: string | null
  applicationStart: Date | null
  applicationEnd: Date | null
  applicationUrl: string | null
  requiredDocuments: string | null
  isCentralGov: boolean
  govLevel: string | null
  infographicUrl: string | null
  cardImageUrl: string | null
  createdAt: Date
  updatedAt: Date
  _count: PolicyCountAggregateOutputType | null
  _avg: PolicyAvgAggregateOutputType | null
  _sum: PolicySumAggregateOutputType | null
  _min: PolicyMinAggregateOutputType | null
  _max: PolicyMaxAggregateOutputType | null
}

type GetPolicyGroupByPayload<T extends PolicyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PolicyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PolicyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PolicyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PolicyGroupByOutputType[P]>
      }
    >
  >



export type PolicyWhereInput = {
  AND?: Prisma.PolicyWhereInput | Prisma.PolicyWhereInput[]
  OR?: Prisma.PolicyWhereInput[]
  NOT?: Prisma.PolicyWhereInput | Prisma.PolicyWhereInput[]
  id?: Prisma.StringFilter<"Policy"> | string
  title?: Prisma.StringFilter<"Policy"> | string
  description?: Prisma.StringNullableFilter<"Policy"> | string | null
  category?: Prisma.StringFilter<"Policy"> | string
  targetCity?: Prisma.StringNullableFilter<"Policy"> | string | null
  targetDistrict?: Prisma.StringNullableFilter<"Policy"> | string | null
  minIncomeLevel?: Prisma.StringNullableFilter<"Policy"> | string | null
  maxIncomeLevel?: Prisma.StringNullableFilter<"Policy"> | string | null
  minChildCount?: Prisma.IntNullableFilter<"Policy"> | number | null
  maxChildCount?: Prisma.IntNullableFilter<"Policy"> | number | null
  minChildAge?: Prisma.IntNullableFilter<"Policy"> | number | null
  maxChildAge?: Prisma.IntNullableFilter<"Policy"> | number | null
  requiresDualIncome?: Prisma.BoolFilter<"Policy"> | boolean
  requiresMultiChild?: Prisma.BoolFilter<"Policy"> | boolean
  benefitAmount?: Prisma.IntNullableFilter<"Policy"> | number | null
  benefitType?: Prisma.StringNullableFilter<"Policy"> | string | null
  benefitDescription?: Prisma.StringNullableFilter<"Policy"> | string | null
  applicationStart?: Prisma.DateTimeNullableFilter<"Policy"> | Date | string | null
  applicationEnd?: Prisma.DateTimeNullableFilter<"Policy"> | Date | string | null
  applicationUrl?: Prisma.StringNullableFilter<"Policy"> | string | null
  requiredDocuments?: Prisma.StringNullableFilter<"Policy"> | string | null
  isCentralGov?: Prisma.BoolFilter<"Policy"> | boolean
  govLevel?: Prisma.StringNullableFilter<"Policy"> | string | null
  infographicUrl?: Prisma.StringNullableFilter<"Policy"> | string | null
  cardImageUrl?: Prisma.StringNullableFilter<"Policy"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Policy"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Policy"> | Date | string
  userPolicies?: Prisma.UserPolicyListRelationFilter
  reviews?: Prisma.ReviewListRelationFilter
}

export type PolicyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrder
  targetCity?: Prisma.SortOrderInput | Prisma.SortOrder
  targetDistrict?: Prisma.SortOrderInput | Prisma.SortOrder
  minIncomeLevel?: Prisma.SortOrderInput | Prisma.SortOrder
  maxIncomeLevel?: Prisma.SortOrderInput | Prisma.SortOrder
  minChildCount?: Prisma.SortOrderInput | Prisma.SortOrder
  maxChildCount?: Prisma.SortOrderInput | Prisma.SortOrder
  minChildAge?: Prisma.SortOrderInput | Prisma.SortOrder
  maxChildAge?: Prisma.SortOrderInput | Prisma.SortOrder
  requiresDualIncome?: Prisma.SortOrder
  requiresMultiChild?: Prisma.SortOrder
  benefitAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  benefitType?: Prisma.SortOrderInput | Prisma.SortOrder
  benefitDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  applicationStart?: Prisma.SortOrderInput | Prisma.SortOrder
  applicationEnd?: Prisma.SortOrderInput | Prisma.SortOrder
  applicationUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  requiredDocuments?: Prisma.SortOrderInput | Prisma.SortOrder
  isCentralGov?: Prisma.SortOrder
  govLevel?: Prisma.SortOrderInput | Prisma.SortOrder
  infographicUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  cardImageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userPolicies?: Prisma.UserPolicyOrderByRelationAggregateInput
  reviews?: Prisma.ReviewOrderByRelationAggregateInput
}

export type PolicyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PolicyWhereInput | Prisma.PolicyWhereInput[]
  OR?: Prisma.PolicyWhereInput[]
  NOT?: Prisma.PolicyWhereInput | Prisma.PolicyWhereInput[]
  title?: Prisma.StringFilter<"Policy"> | string
  description?: Prisma.StringNullableFilter<"Policy"> | string | null
  category?: Prisma.StringFilter<"Policy"> | string
  targetCity?: Prisma.StringNullableFilter<"Policy"> | string | null
  targetDistrict?: Prisma.StringNullableFilter<"Policy"> | string | null
  minIncomeLevel?: Prisma.StringNullableFilter<"Policy"> | string | null
  maxIncomeLevel?: Prisma.StringNullableFilter<"Policy"> | string | null
  minChildCount?: Prisma.IntNullableFilter<"Policy"> | number | null
  maxChildCount?: Prisma.IntNullableFilter<"Policy"> | number | null
  minChildAge?: Prisma.IntNullableFilter<"Policy"> | number | null
  maxChildAge?: Prisma.IntNullableFilter<"Policy"> | number | null
  requiresDualIncome?: Prisma.BoolFilter<"Policy"> | boolean
  requiresMultiChild?: Prisma.BoolFilter<"Policy"> | boolean
  benefitAmount?: Prisma.IntNullableFilter<"Policy"> | number | null
  benefitType?: Prisma.StringNullableFilter<"Policy"> | string | null
  benefitDescription?: Prisma.StringNullableFilter<"Policy"> | string | null
  applicationStart?: Prisma.DateTimeNullableFilter<"Policy"> | Date | string | null
  applicationEnd?: Prisma.DateTimeNullableFilter<"Policy"> | Date | string | null
  applicationUrl?: Prisma.StringNullableFilter<"Policy"> | string | null
  requiredDocuments?: Prisma.StringNullableFilter<"Policy"> | string | null
  isCentralGov?: Prisma.BoolFilter<"Policy"> | boolean
  govLevel?: Prisma.StringNullableFilter<"Policy"> | string | null
  infographicUrl?: Prisma.StringNullableFilter<"Policy"> | string | null
  cardImageUrl?: Prisma.StringNullableFilter<"Policy"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Policy"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Policy"> | Date | string
  userPolicies?: Prisma.UserPolicyListRelationFilter
  reviews?: Prisma.ReviewListRelationFilter
}, "id">

export type PolicyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrder
  targetCity?: Prisma.SortOrderInput | Prisma.SortOrder
  targetDistrict?: Prisma.SortOrderInput | Prisma.SortOrder
  minIncomeLevel?: Prisma.SortOrderInput | Prisma.SortOrder
  maxIncomeLevel?: Prisma.SortOrderInput | Prisma.SortOrder
  minChildCount?: Prisma.SortOrderInput | Prisma.SortOrder
  maxChildCount?: Prisma.SortOrderInput | Prisma.SortOrder
  minChildAge?: Prisma.SortOrderInput | Prisma.SortOrder
  maxChildAge?: Prisma.SortOrderInput | Prisma.SortOrder
  requiresDualIncome?: Prisma.SortOrder
  requiresMultiChild?: Prisma.SortOrder
  benefitAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  benefitType?: Prisma.SortOrderInput | Prisma.SortOrder
  benefitDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  applicationStart?: Prisma.SortOrderInput | Prisma.SortOrder
  applicationEnd?: Prisma.SortOrderInput | Prisma.SortOrder
  applicationUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  requiredDocuments?: Prisma.SortOrderInput | Prisma.SortOrder
  isCentralGov?: Prisma.SortOrder
  govLevel?: Prisma.SortOrderInput | Prisma.SortOrder
  infographicUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  cardImageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PolicyCountOrderByAggregateInput
  _avg?: Prisma.PolicyAvgOrderByAggregateInput
  _max?: Prisma.PolicyMaxOrderByAggregateInput
  _min?: Prisma.PolicyMinOrderByAggregateInput
  _sum?: Prisma.PolicySumOrderByAggregateInput
}

export type PolicyScalarWhereWithAggregatesInput = {
  AND?: Prisma.PolicyScalarWhereWithAggregatesInput | Prisma.PolicyScalarWhereWithAggregatesInput[]
  OR?: Prisma.PolicyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PolicyScalarWhereWithAggregatesInput | Prisma.PolicyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Policy"> | string
  title?: Prisma.StringWithAggregatesFilter<"Policy"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  category?: Prisma.StringWithAggregatesFilter<"Policy"> | string
  targetCity?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  targetDistrict?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  minIncomeLevel?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  maxIncomeLevel?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  minChildCount?: Prisma.IntNullableWithAggregatesFilter<"Policy"> | number | null
  maxChildCount?: Prisma.IntNullableWithAggregatesFilter<"Policy"> | number | null
  minChildAge?: Prisma.IntNullableWithAggregatesFilter<"Policy"> | number | null
  maxChildAge?: Prisma.IntNullableWithAggregatesFilter<"Policy"> | number | null
  requiresDualIncome?: Prisma.BoolWithAggregatesFilter<"Policy"> | boolean
  requiresMultiChild?: Prisma.BoolWithAggregatesFilter<"Policy"> | boolean
  benefitAmount?: Prisma.IntNullableWithAggregatesFilter<"Policy"> | number | null
  benefitType?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  benefitDescription?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  applicationStart?: Prisma.DateTimeNullableWithAggregatesFilter<"Policy"> | Date | string | null
  applicationEnd?: Prisma.DateTimeNullableWithAggregatesFilter<"Policy"> | Date | string | null
  applicationUrl?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  requiredDocuments?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  isCentralGov?: Prisma.BoolWithAggregatesFilter<"Policy"> | boolean
  govLevel?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  infographicUrl?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  cardImageUrl?: Prisma.StringNullableWithAggregatesFilter<"Policy"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Policy"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Policy"> | Date | string
}

export type PolicyCreateInput = {
  id?: string
  title: string
  description?: string | null
  category: string
  targetCity?: string | null
  targetDistrict?: string | null
  minIncomeLevel?: string | null
  maxIncomeLevel?: string | null
  minChildCount?: number | null
  maxChildCount?: number | null
  minChildAge?: number | null
  maxChildAge?: number | null
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: number | null
  benefitType?: string | null
  benefitDescription?: string | null
  applicationStart?: Date | string | null
  applicationEnd?: Date | string | null
  applicationUrl?: string | null
  requiredDocuments?: string | null
  isCentralGov?: boolean
  govLevel?: string | null
  infographicUrl?: string | null
  cardImageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userPolicies?: Prisma.UserPolicyCreateNestedManyWithoutPolicyInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPolicyInput
}

export type PolicyUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  category: string
  targetCity?: string | null
  targetDistrict?: string | null
  minIncomeLevel?: string | null
  maxIncomeLevel?: string | null
  minChildCount?: number | null
  maxChildCount?: number | null
  minChildAge?: number | null
  maxChildAge?: number | null
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: number | null
  benefitType?: string | null
  benefitDescription?: string | null
  applicationStart?: Date | string | null
  applicationEnd?: Date | string | null
  applicationUrl?: string | null
  requiredDocuments?: string | null
  isCentralGov?: boolean
  govLevel?: string | null
  infographicUrl?: string | null
  cardImageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userPolicies?: Prisma.UserPolicyUncheckedCreateNestedManyWithoutPolicyInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPolicyInput
}

export type PolicyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  targetCity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetDistrict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maxIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiresDualIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresMultiChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  benefitAmount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  benefitType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefitDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  applicationStart?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationEnd?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requiredDocuments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCentralGov?: Prisma.BoolFieldUpdateOperationsInput | boolean
  govLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  infographicUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cardImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userPolicies?: Prisma.UserPolicyUpdateManyWithoutPolicyNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPolicyNestedInput
}

export type PolicyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  targetCity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetDistrict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maxIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiresDualIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresMultiChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  benefitAmount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  benefitType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefitDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  applicationStart?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationEnd?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requiredDocuments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCentralGov?: Prisma.BoolFieldUpdateOperationsInput | boolean
  govLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  infographicUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cardImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userPolicies?: Prisma.UserPolicyUncheckedUpdateManyWithoutPolicyNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPolicyNestedInput
}

export type PolicyCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  category: string
  targetCity?: string | null
  targetDistrict?: string | null
  minIncomeLevel?: string | null
  maxIncomeLevel?: string | null
  minChildCount?: number | null
  maxChildCount?: number | null
  minChildAge?: number | null
  maxChildAge?: number | null
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: number | null
  benefitType?: string | null
  benefitDescription?: string | null
  applicationStart?: Date | string | null
  applicationEnd?: Date | string | null
  applicationUrl?: string | null
  requiredDocuments?: string | null
  isCentralGov?: boolean
  govLevel?: string | null
  infographicUrl?: string | null
  cardImageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PolicyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  targetCity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetDistrict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maxIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiresDualIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresMultiChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  benefitAmount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  benefitType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefitDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  applicationStart?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationEnd?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requiredDocuments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCentralGov?: Prisma.BoolFieldUpdateOperationsInput | boolean
  govLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  infographicUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cardImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PolicyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  targetCity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetDistrict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maxIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiresDualIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresMultiChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  benefitAmount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  benefitType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefitDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  applicationStart?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationEnd?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requiredDocuments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCentralGov?: Prisma.BoolFieldUpdateOperationsInput | boolean
  govLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  infographicUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cardImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PolicyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  targetCity?: Prisma.SortOrder
  targetDistrict?: Prisma.SortOrder
  minIncomeLevel?: Prisma.SortOrder
  maxIncomeLevel?: Prisma.SortOrder
  minChildCount?: Prisma.SortOrder
  maxChildCount?: Prisma.SortOrder
  minChildAge?: Prisma.SortOrder
  maxChildAge?: Prisma.SortOrder
  requiresDualIncome?: Prisma.SortOrder
  requiresMultiChild?: Prisma.SortOrder
  benefitAmount?: Prisma.SortOrder
  benefitType?: Prisma.SortOrder
  benefitDescription?: Prisma.SortOrder
  applicationStart?: Prisma.SortOrder
  applicationEnd?: Prisma.SortOrder
  applicationUrl?: Prisma.SortOrder
  requiredDocuments?: Prisma.SortOrder
  isCentralGov?: Prisma.SortOrder
  govLevel?: Prisma.SortOrder
  infographicUrl?: Prisma.SortOrder
  cardImageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PolicyAvgOrderByAggregateInput = {
  minChildCount?: Prisma.SortOrder
  maxChildCount?: Prisma.SortOrder
  minChildAge?: Prisma.SortOrder
  maxChildAge?: Prisma.SortOrder
  benefitAmount?: Prisma.SortOrder
}

export type PolicyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  targetCity?: Prisma.SortOrder
  targetDistrict?: Prisma.SortOrder
  minIncomeLevel?: Prisma.SortOrder
  maxIncomeLevel?: Prisma.SortOrder
  minChildCount?: Prisma.SortOrder
  maxChildCount?: Prisma.SortOrder
  minChildAge?: Prisma.SortOrder
  maxChildAge?: Prisma.SortOrder
  requiresDualIncome?: Prisma.SortOrder
  requiresMultiChild?: Prisma.SortOrder
  benefitAmount?: Prisma.SortOrder
  benefitType?: Prisma.SortOrder
  benefitDescription?: Prisma.SortOrder
  applicationStart?: Prisma.SortOrder
  applicationEnd?: Prisma.SortOrder
  applicationUrl?: Prisma.SortOrder
  requiredDocuments?: Prisma.SortOrder
  isCentralGov?: Prisma.SortOrder
  govLevel?: Prisma.SortOrder
  infographicUrl?: Prisma.SortOrder
  cardImageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PolicyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  targetCity?: Prisma.SortOrder
  targetDistrict?: Prisma.SortOrder
  minIncomeLevel?: Prisma.SortOrder
  maxIncomeLevel?: Prisma.SortOrder
  minChildCount?: Prisma.SortOrder
  maxChildCount?: Prisma.SortOrder
  minChildAge?: Prisma.SortOrder
  maxChildAge?: Prisma.SortOrder
  requiresDualIncome?: Prisma.SortOrder
  requiresMultiChild?: Prisma.SortOrder
  benefitAmount?: Prisma.SortOrder
  benefitType?: Prisma.SortOrder
  benefitDescription?: Prisma.SortOrder
  applicationStart?: Prisma.SortOrder
  applicationEnd?: Prisma.SortOrder
  applicationUrl?: Prisma.SortOrder
  requiredDocuments?: Prisma.SortOrder
  isCentralGov?: Prisma.SortOrder
  govLevel?: Prisma.SortOrder
  infographicUrl?: Prisma.SortOrder
  cardImageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PolicySumOrderByAggregateInput = {
  minChildCount?: Prisma.SortOrder
  maxChildCount?: Prisma.SortOrder
  minChildAge?: Prisma.SortOrder
  maxChildAge?: Prisma.SortOrder
  benefitAmount?: Prisma.SortOrder
}

export type PolicyScalarRelationFilter = {
  is?: Prisma.PolicyWhereInput
  isNot?: Prisma.PolicyWhereInput
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type PolicyCreateNestedOneWithoutUserPoliciesInput = {
  create?: Prisma.XOR<Prisma.PolicyCreateWithoutUserPoliciesInput, Prisma.PolicyUncheckedCreateWithoutUserPoliciesInput>
  connectOrCreate?: Prisma.PolicyCreateOrConnectWithoutUserPoliciesInput
  connect?: Prisma.PolicyWhereUniqueInput
}

export type PolicyUpdateOneRequiredWithoutUserPoliciesNestedInput = {
  create?: Prisma.XOR<Prisma.PolicyCreateWithoutUserPoliciesInput, Prisma.PolicyUncheckedCreateWithoutUserPoliciesInput>
  connectOrCreate?: Prisma.PolicyCreateOrConnectWithoutUserPoliciesInput
  upsert?: Prisma.PolicyUpsertWithoutUserPoliciesInput
  connect?: Prisma.PolicyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PolicyUpdateToOneWithWhereWithoutUserPoliciesInput, Prisma.PolicyUpdateWithoutUserPoliciesInput>, Prisma.PolicyUncheckedUpdateWithoutUserPoliciesInput>
}

export type PolicyCreateNestedOneWithoutReviewsInput = {
  create?: Prisma.XOR<Prisma.PolicyCreateWithoutReviewsInput, Prisma.PolicyUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.PolicyCreateOrConnectWithoutReviewsInput
  connect?: Prisma.PolicyWhereUniqueInput
}

export type PolicyUpdateOneRequiredWithoutReviewsNestedInput = {
  create?: Prisma.XOR<Prisma.PolicyCreateWithoutReviewsInput, Prisma.PolicyUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.PolicyCreateOrConnectWithoutReviewsInput
  upsert?: Prisma.PolicyUpsertWithoutReviewsInput
  connect?: Prisma.PolicyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PolicyUpdateToOneWithWhereWithoutReviewsInput, Prisma.PolicyUpdateWithoutReviewsInput>, Prisma.PolicyUncheckedUpdateWithoutReviewsInput>
}

export type PolicyCreateWithoutUserPoliciesInput = {
  id?: string
  title: string
  description?: string | null
  category: string
  targetCity?: string | null
  targetDistrict?: string | null
  minIncomeLevel?: string | null
  maxIncomeLevel?: string | null
  minChildCount?: number | null
  maxChildCount?: number | null
  minChildAge?: number | null
  maxChildAge?: number | null
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: number | null
  benefitType?: string | null
  benefitDescription?: string | null
  applicationStart?: Date | string | null
  applicationEnd?: Date | string | null
  applicationUrl?: string | null
  requiredDocuments?: string | null
  isCentralGov?: boolean
  govLevel?: string | null
  infographicUrl?: string | null
  cardImageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  reviews?: Prisma.ReviewCreateNestedManyWithoutPolicyInput
}

export type PolicyUncheckedCreateWithoutUserPoliciesInput = {
  id?: string
  title: string
  description?: string | null
  category: string
  targetCity?: string | null
  targetDistrict?: string | null
  minIncomeLevel?: string | null
  maxIncomeLevel?: string | null
  minChildCount?: number | null
  maxChildCount?: number | null
  minChildAge?: number | null
  maxChildAge?: number | null
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: number | null
  benefitType?: string | null
  benefitDescription?: string | null
  applicationStart?: Date | string | null
  applicationEnd?: Date | string | null
  applicationUrl?: string | null
  requiredDocuments?: string | null
  isCentralGov?: boolean
  govLevel?: string | null
  infographicUrl?: string | null
  cardImageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPolicyInput
}

export type PolicyCreateOrConnectWithoutUserPoliciesInput = {
  where: Prisma.PolicyWhereUniqueInput
  create: Prisma.XOR<Prisma.PolicyCreateWithoutUserPoliciesInput, Prisma.PolicyUncheckedCreateWithoutUserPoliciesInput>
}

export type PolicyUpsertWithoutUserPoliciesInput = {
  update: Prisma.XOR<Prisma.PolicyUpdateWithoutUserPoliciesInput, Prisma.PolicyUncheckedUpdateWithoutUserPoliciesInput>
  create: Prisma.XOR<Prisma.PolicyCreateWithoutUserPoliciesInput, Prisma.PolicyUncheckedCreateWithoutUserPoliciesInput>
  where?: Prisma.PolicyWhereInput
}

export type PolicyUpdateToOneWithWhereWithoutUserPoliciesInput = {
  where?: Prisma.PolicyWhereInput
  data: Prisma.XOR<Prisma.PolicyUpdateWithoutUserPoliciesInput, Prisma.PolicyUncheckedUpdateWithoutUserPoliciesInput>
}

export type PolicyUpdateWithoutUserPoliciesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  targetCity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetDistrict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maxIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiresDualIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresMultiChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  benefitAmount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  benefitType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefitDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  applicationStart?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationEnd?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requiredDocuments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCentralGov?: Prisma.BoolFieldUpdateOperationsInput | boolean
  govLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  infographicUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cardImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviews?: Prisma.ReviewUpdateManyWithoutPolicyNestedInput
}

export type PolicyUncheckedUpdateWithoutUserPoliciesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  targetCity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetDistrict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maxIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiresDualIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresMultiChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  benefitAmount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  benefitType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefitDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  applicationStart?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationEnd?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requiredDocuments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCentralGov?: Prisma.BoolFieldUpdateOperationsInput | boolean
  govLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  infographicUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cardImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPolicyNestedInput
}

export type PolicyCreateWithoutReviewsInput = {
  id?: string
  title: string
  description?: string | null
  category: string
  targetCity?: string | null
  targetDistrict?: string | null
  minIncomeLevel?: string | null
  maxIncomeLevel?: string | null
  minChildCount?: number | null
  maxChildCount?: number | null
  minChildAge?: number | null
  maxChildAge?: number | null
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: number | null
  benefitType?: string | null
  benefitDescription?: string | null
  applicationStart?: Date | string | null
  applicationEnd?: Date | string | null
  applicationUrl?: string | null
  requiredDocuments?: string | null
  isCentralGov?: boolean
  govLevel?: string | null
  infographicUrl?: string | null
  cardImageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userPolicies?: Prisma.UserPolicyCreateNestedManyWithoutPolicyInput
}

export type PolicyUncheckedCreateWithoutReviewsInput = {
  id?: string
  title: string
  description?: string | null
  category: string
  targetCity?: string | null
  targetDistrict?: string | null
  minIncomeLevel?: string | null
  maxIncomeLevel?: string | null
  minChildCount?: number | null
  maxChildCount?: number | null
  minChildAge?: number | null
  maxChildAge?: number | null
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: number | null
  benefitType?: string | null
  benefitDescription?: string | null
  applicationStart?: Date | string | null
  applicationEnd?: Date | string | null
  applicationUrl?: string | null
  requiredDocuments?: string | null
  isCentralGov?: boolean
  govLevel?: string | null
  infographicUrl?: string | null
  cardImageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userPolicies?: Prisma.UserPolicyUncheckedCreateNestedManyWithoutPolicyInput
}

export type PolicyCreateOrConnectWithoutReviewsInput = {
  where: Prisma.PolicyWhereUniqueInput
  create: Prisma.XOR<Prisma.PolicyCreateWithoutReviewsInput, Prisma.PolicyUncheckedCreateWithoutReviewsInput>
}

export type PolicyUpsertWithoutReviewsInput = {
  update: Prisma.XOR<Prisma.PolicyUpdateWithoutReviewsInput, Prisma.PolicyUncheckedUpdateWithoutReviewsInput>
  create: Prisma.XOR<Prisma.PolicyCreateWithoutReviewsInput, Prisma.PolicyUncheckedCreateWithoutReviewsInput>
  where?: Prisma.PolicyWhereInput
}

export type PolicyUpdateToOneWithWhereWithoutReviewsInput = {
  where?: Prisma.PolicyWhereInput
  data: Prisma.XOR<Prisma.PolicyUpdateWithoutReviewsInput, Prisma.PolicyUncheckedUpdateWithoutReviewsInput>
}

export type PolicyUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  targetCity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetDistrict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maxIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiresDualIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresMultiChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  benefitAmount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  benefitType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefitDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  applicationStart?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationEnd?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requiredDocuments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCentralGov?: Prisma.BoolFieldUpdateOperationsInput | boolean
  govLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  infographicUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cardImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userPolicies?: Prisma.UserPolicyUpdateManyWithoutPolicyNestedInput
}

export type PolicyUncheckedUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  targetCity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  targetDistrict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maxIncomeLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxChildAge?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  requiresDualIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresMultiChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  benefitAmount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  benefitType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefitDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  applicationStart?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationEnd?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  applicationUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requiredDocuments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCentralGov?: Prisma.BoolFieldUpdateOperationsInput | boolean
  govLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  infographicUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cardImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userPolicies?: Prisma.UserPolicyUncheckedUpdateManyWithoutPolicyNestedInput
}


/**
 * Count Type PolicyCountOutputType
 */

export type PolicyCountOutputType = {
  userPolicies: number
  reviews: number
}

export type PolicyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userPolicies?: boolean | PolicyCountOutputTypeCountUserPoliciesArgs
  reviews?: boolean | PolicyCountOutputTypeCountReviewsArgs
}

/**
 * PolicyCountOutputType without action
 */
export type PolicyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PolicyCountOutputType
   */
  select?: Prisma.PolicyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PolicyCountOutputType without action
 */
export type PolicyCountOutputTypeCountUserPoliciesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserPolicyWhereInput
}

/**
 * PolicyCountOutputType without action
 */
export type PolicyCountOutputTypeCountReviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReviewWhereInput
}


export type PolicySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  targetCity?: boolean
  targetDistrict?: boolean
  minIncomeLevel?: boolean
  maxIncomeLevel?: boolean
  minChildCount?: boolean
  maxChildCount?: boolean
  minChildAge?: boolean
  maxChildAge?: boolean
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: boolean
  benefitType?: boolean
  benefitDescription?: boolean
  applicationStart?: boolean
  applicationEnd?: boolean
  applicationUrl?: boolean
  requiredDocuments?: boolean
  isCentralGov?: boolean
  govLevel?: boolean
  infographicUrl?: boolean
  cardImageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userPolicies?: boolean | Prisma.Policy$userPoliciesArgs<ExtArgs>
  reviews?: boolean | Prisma.Policy$reviewsArgs<ExtArgs>
  _count?: boolean | Prisma.PolicyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["policy"]>

export type PolicySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  targetCity?: boolean
  targetDistrict?: boolean
  minIncomeLevel?: boolean
  maxIncomeLevel?: boolean
  minChildCount?: boolean
  maxChildCount?: boolean
  minChildAge?: boolean
  maxChildAge?: boolean
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: boolean
  benefitType?: boolean
  benefitDescription?: boolean
  applicationStart?: boolean
  applicationEnd?: boolean
  applicationUrl?: boolean
  requiredDocuments?: boolean
  isCentralGov?: boolean
  govLevel?: boolean
  infographicUrl?: boolean
  cardImageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["policy"]>

export type PolicySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  targetCity?: boolean
  targetDistrict?: boolean
  minIncomeLevel?: boolean
  maxIncomeLevel?: boolean
  minChildCount?: boolean
  maxChildCount?: boolean
  minChildAge?: boolean
  maxChildAge?: boolean
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: boolean
  benefitType?: boolean
  benefitDescription?: boolean
  applicationStart?: boolean
  applicationEnd?: boolean
  applicationUrl?: boolean
  requiredDocuments?: boolean
  isCentralGov?: boolean
  govLevel?: boolean
  infographicUrl?: boolean
  cardImageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["policy"]>

export type PolicySelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  targetCity?: boolean
  targetDistrict?: boolean
  minIncomeLevel?: boolean
  maxIncomeLevel?: boolean
  minChildCount?: boolean
  maxChildCount?: boolean
  minChildAge?: boolean
  maxChildAge?: boolean
  requiresDualIncome?: boolean
  requiresMultiChild?: boolean
  benefitAmount?: boolean
  benefitType?: boolean
  benefitDescription?: boolean
  applicationStart?: boolean
  applicationEnd?: boolean
  applicationUrl?: boolean
  requiredDocuments?: boolean
  isCentralGov?: boolean
  govLevel?: boolean
  infographicUrl?: boolean
  cardImageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PolicyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "category" | "targetCity" | "targetDistrict" | "minIncomeLevel" | "maxIncomeLevel" | "minChildCount" | "maxChildCount" | "minChildAge" | "maxChildAge" | "requiresDualIncome" | "requiresMultiChild" | "benefitAmount" | "benefitType" | "benefitDescription" | "applicationStart" | "applicationEnd" | "applicationUrl" | "requiredDocuments" | "isCentralGov" | "govLevel" | "infographicUrl" | "cardImageUrl" | "createdAt" | "updatedAt", ExtArgs["result"]["policy"]>
export type PolicyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userPolicies?: boolean | Prisma.Policy$userPoliciesArgs<ExtArgs>
  reviews?: boolean | Prisma.Policy$reviewsArgs<ExtArgs>
  _count?: boolean | Prisma.PolicyCountOutputTypeDefaultArgs<ExtArgs>
}
export type PolicyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PolicyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PolicyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Policy"
  objects: {
    userPolicies: Prisma.$UserPolicyPayload<ExtArgs>[]
    reviews: Prisma.$ReviewPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    category: string
    targetCity: string | null
    targetDistrict: string | null
    minIncomeLevel: string | null
    maxIncomeLevel: string | null
    minChildCount: number | null
    maxChildCount: number | null
    minChildAge: number | null
    maxChildAge: number | null
    requiresDualIncome: boolean
    requiresMultiChild: boolean
    benefitAmount: number | null
    benefitType: string | null
    benefitDescription: string | null
    applicationStart: Date | null
    applicationEnd: Date | null
    applicationUrl: string | null
    requiredDocuments: string | null
    isCentralGov: boolean
    govLevel: string | null
    infographicUrl: string | null
    cardImageUrl: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["policy"]>
  composites: {}
}

export type PolicyGetPayload<S extends boolean | null | undefined | PolicyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PolicyPayload, S>

export type PolicyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PolicyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PolicyCountAggregateInputType | true
  }

export interface PolicyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Policy'], meta: { name: 'Policy' } }
  /**
   * Find zero or one Policy that matches the filter.
   * @param {PolicyFindUniqueArgs} args - Arguments to find a Policy
   * @example
   * // Get one Policy
   * const policy = await prisma.policy.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PolicyFindUniqueArgs>(args: Prisma.SelectSubset<T, PolicyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PolicyClient<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Policy that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PolicyFindUniqueOrThrowArgs} args - Arguments to find a Policy
   * @example
   * // Get one Policy
   * const policy = await prisma.policy.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PolicyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PolicyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PolicyClient<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Policy that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyFindFirstArgs} args - Arguments to find a Policy
   * @example
   * // Get one Policy
   * const policy = await prisma.policy.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PolicyFindFirstArgs>(args?: Prisma.SelectSubset<T, PolicyFindFirstArgs<ExtArgs>>): Prisma.Prisma__PolicyClient<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Policy that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyFindFirstOrThrowArgs} args - Arguments to find a Policy
   * @example
   * // Get one Policy
   * const policy = await prisma.policy.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PolicyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PolicyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PolicyClient<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Policies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Policies
   * const policies = await prisma.policy.findMany()
   * 
   * // Get first 10 Policies
   * const policies = await prisma.policy.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const policyWithIdOnly = await prisma.policy.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PolicyFindManyArgs>(args?: Prisma.SelectSubset<T, PolicyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Policy.
   * @param {PolicyCreateArgs} args - Arguments to create a Policy.
   * @example
   * // Create one Policy
   * const Policy = await prisma.policy.create({
   *   data: {
   *     // ... data to create a Policy
   *   }
   * })
   * 
   */
  create<T extends PolicyCreateArgs>(args: Prisma.SelectSubset<T, PolicyCreateArgs<ExtArgs>>): Prisma.Prisma__PolicyClient<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Policies.
   * @param {PolicyCreateManyArgs} args - Arguments to create many Policies.
   * @example
   * // Create many Policies
   * const policy = await prisma.policy.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PolicyCreateManyArgs>(args?: Prisma.SelectSubset<T, PolicyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Policies and returns the data saved in the database.
   * @param {PolicyCreateManyAndReturnArgs} args - Arguments to create many Policies.
   * @example
   * // Create many Policies
   * const policy = await prisma.policy.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Policies and only return the `id`
   * const policyWithIdOnly = await prisma.policy.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PolicyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PolicyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Policy.
   * @param {PolicyDeleteArgs} args - Arguments to delete one Policy.
   * @example
   * // Delete one Policy
   * const Policy = await prisma.policy.delete({
   *   where: {
   *     // ... filter to delete one Policy
   *   }
   * })
   * 
   */
  delete<T extends PolicyDeleteArgs>(args: Prisma.SelectSubset<T, PolicyDeleteArgs<ExtArgs>>): Prisma.Prisma__PolicyClient<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Policy.
   * @param {PolicyUpdateArgs} args - Arguments to update one Policy.
   * @example
   * // Update one Policy
   * const policy = await prisma.policy.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PolicyUpdateArgs>(args: Prisma.SelectSubset<T, PolicyUpdateArgs<ExtArgs>>): Prisma.Prisma__PolicyClient<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Policies.
   * @param {PolicyDeleteManyArgs} args - Arguments to filter Policies to delete.
   * @example
   * // Delete a few Policies
   * const { count } = await prisma.policy.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PolicyDeleteManyArgs>(args?: Prisma.SelectSubset<T, PolicyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Policies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Policies
   * const policy = await prisma.policy.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PolicyUpdateManyArgs>(args: Prisma.SelectSubset<T, PolicyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Policies and returns the data updated in the database.
   * @param {PolicyUpdateManyAndReturnArgs} args - Arguments to update many Policies.
   * @example
   * // Update many Policies
   * const policy = await prisma.policy.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Policies and only return the `id`
   * const policyWithIdOnly = await prisma.policy.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PolicyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PolicyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Policy.
   * @param {PolicyUpsertArgs} args - Arguments to update or create a Policy.
   * @example
   * // Update or create a Policy
   * const policy = await prisma.policy.upsert({
   *   create: {
   *     // ... data to create a Policy
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Policy we want to update
   *   }
   * })
   */
  upsert<T extends PolicyUpsertArgs>(args: Prisma.SelectSubset<T, PolicyUpsertArgs<ExtArgs>>): Prisma.Prisma__PolicyClient<runtime.Types.Result.GetResult<Prisma.$PolicyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Policies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyCountArgs} args - Arguments to filter Policies to count.
   * @example
   * // Count the number of Policies
   * const count = await prisma.policy.count({
   *   where: {
   *     // ... the filter for the Policies we want to count
   *   }
   * })
  **/
  count<T extends PolicyCountArgs>(
    args?: Prisma.Subset<T, PolicyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PolicyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Policy.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PolicyAggregateArgs>(args: Prisma.Subset<T, PolicyAggregateArgs>): Prisma.PrismaPromise<GetPolicyAggregateType<T>>

  /**
   * Group by Policy.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PolicyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PolicyGroupByArgs['orderBy'] }
      : { orderBy?: PolicyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PolicyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPolicyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Policy model
 */
readonly fields: PolicyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Policy.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PolicyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  userPolicies<T extends Prisma.Policy$userPoliciesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Policy$userPoliciesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPolicyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  reviews<T extends Prisma.Policy$reviewsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Policy$reviewsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Policy model
 */
export interface PolicyFieldRefs {
  readonly id: Prisma.FieldRef<"Policy", 'String'>
  readonly title: Prisma.FieldRef<"Policy", 'String'>
  readonly description: Prisma.FieldRef<"Policy", 'String'>
  readonly category: Prisma.FieldRef<"Policy", 'String'>
  readonly targetCity: Prisma.FieldRef<"Policy", 'String'>
  readonly targetDistrict: Prisma.FieldRef<"Policy", 'String'>
  readonly minIncomeLevel: Prisma.FieldRef<"Policy", 'String'>
  readonly maxIncomeLevel: Prisma.FieldRef<"Policy", 'String'>
  readonly minChildCount: Prisma.FieldRef<"Policy", 'Int'>
  readonly maxChildCount: Prisma.FieldRef<"Policy", 'Int'>
  readonly minChildAge: Prisma.FieldRef<"Policy", 'Int'>
  readonly maxChildAge: Prisma.FieldRef<"Policy", 'Int'>
  readonly requiresDualIncome: Prisma.FieldRef<"Policy", 'Boolean'>
  readonly requiresMultiChild: Prisma.FieldRef<"Policy", 'Boolean'>
  readonly benefitAmount: Prisma.FieldRef<"Policy", 'Int'>
  readonly benefitType: Prisma.FieldRef<"Policy", 'String'>
  readonly benefitDescription: Prisma.FieldRef<"Policy", 'String'>
  readonly applicationStart: Prisma.FieldRef<"Policy", 'DateTime'>
  readonly applicationEnd: Prisma.FieldRef<"Policy", 'DateTime'>
  readonly applicationUrl: Prisma.FieldRef<"Policy", 'String'>
  readonly requiredDocuments: Prisma.FieldRef<"Policy", 'String'>
  readonly isCentralGov: Prisma.FieldRef<"Policy", 'Boolean'>
  readonly govLevel: Prisma.FieldRef<"Policy", 'String'>
  readonly infographicUrl: Prisma.FieldRef<"Policy", 'String'>
  readonly cardImageUrl: Prisma.FieldRef<"Policy", 'String'>
  readonly createdAt: Prisma.FieldRef<"Policy", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Policy", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Policy findUnique
 */
export type PolicyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
  /**
   * Filter, which Policy to fetch.
   */
  where: Prisma.PolicyWhereUniqueInput
}

/**
 * Policy findUniqueOrThrow
 */
export type PolicyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
  /**
   * Filter, which Policy to fetch.
   */
  where: Prisma.PolicyWhereUniqueInput
}

/**
 * Policy findFirst
 */
export type PolicyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
  /**
   * Filter, which Policy to fetch.
   */
  where?: Prisma.PolicyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Policies to fetch.
   */
  orderBy?: Prisma.PolicyOrderByWithRelationInput | Prisma.PolicyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Policies.
   */
  cursor?: Prisma.PolicyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Policies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Policies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Policies.
   */
  distinct?: Prisma.PolicyScalarFieldEnum | Prisma.PolicyScalarFieldEnum[]
}

/**
 * Policy findFirstOrThrow
 */
export type PolicyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
  /**
   * Filter, which Policy to fetch.
   */
  where?: Prisma.PolicyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Policies to fetch.
   */
  orderBy?: Prisma.PolicyOrderByWithRelationInput | Prisma.PolicyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Policies.
   */
  cursor?: Prisma.PolicyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Policies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Policies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Policies.
   */
  distinct?: Prisma.PolicyScalarFieldEnum | Prisma.PolicyScalarFieldEnum[]
}

/**
 * Policy findMany
 */
export type PolicyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
  /**
   * Filter, which Policies to fetch.
   */
  where?: Prisma.PolicyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Policies to fetch.
   */
  orderBy?: Prisma.PolicyOrderByWithRelationInput | Prisma.PolicyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Policies.
   */
  cursor?: Prisma.PolicyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Policies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Policies.
   */
  skip?: number
  distinct?: Prisma.PolicyScalarFieldEnum | Prisma.PolicyScalarFieldEnum[]
}

/**
 * Policy create
 */
export type PolicyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
  /**
   * The data needed to create a Policy.
   */
  data: Prisma.XOR<Prisma.PolicyCreateInput, Prisma.PolicyUncheckedCreateInput>
}

/**
 * Policy createMany
 */
export type PolicyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Policies.
   */
  data: Prisma.PolicyCreateManyInput | Prisma.PolicyCreateManyInput[]
}

/**
 * Policy createManyAndReturn
 */
export type PolicyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * The data used to create many Policies.
   */
  data: Prisma.PolicyCreateManyInput | Prisma.PolicyCreateManyInput[]
}

/**
 * Policy update
 */
export type PolicyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
  /**
   * The data needed to update a Policy.
   */
  data: Prisma.XOR<Prisma.PolicyUpdateInput, Prisma.PolicyUncheckedUpdateInput>
  /**
   * Choose, which Policy to update.
   */
  where: Prisma.PolicyWhereUniqueInput
}

/**
 * Policy updateMany
 */
export type PolicyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Policies.
   */
  data: Prisma.XOR<Prisma.PolicyUpdateManyMutationInput, Prisma.PolicyUncheckedUpdateManyInput>
  /**
   * Filter which Policies to update
   */
  where?: Prisma.PolicyWhereInput
  /**
   * Limit how many Policies to update.
   */
  limit?: number
}

/**
 * Policy updateManyAndReturn
 */
export type PolicyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * The data used to update Policies.
   */
  data: Prisma.XOR<Prisma.PolicyUpdateManyMutationInput, Prisma.PolicyUncheckedUpdateManyInput>
  /**
   * Filter which Policies to update
   */
  where?: Prisma.PolicyWhereInput
  /**
   * Limit how many Policies to update.
   */
  limit?: number
}

/**
 * Policy upsert
 */
export type PolicyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
  /**
   * The filter to search for the Policy to update in case it exists.
   */
  where: Prisma.PolicyWhereUniqueInput
  /**
   * In case the Policy found by the `where` argument doesn't exist, create a new Policy with this data.
   */
  create: Prisma.XOR<Prisma.PolicyCreateInput, Prisma.PolicyUncheckedCreateInput>
  /**
   * In case the Policy was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PolicyUpdateInput, Prisma.PolicyUncheckedUpdateInput>
}

/**
 * Policy delete
 */
export type PolicyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
  /**
   * Filter which Policy to delete.
   */
  where: Prisma.PolicyWhereUniqueInput
}

/**
 * Policy deleteMany
 */
export type PolicyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Policies to delete
   */
  where?: Prisma.PolicyWhereInput
  /**
   * Limit how many Policies to delete.
   */
  limit?: number
}

/**
 * Policy.userPolicies
 */
export type Policy$userPoliciesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPolicy
   */
  select?: Prisma.UserPolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPolicy
   */
  omit?: Prisma.UserPolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPolicyInclude<ExtArgs> | null
  where?: Prisma.UserPolicyWhereInput
  orderBy?: Prisma.UserPolicyOrderByWithRelationInput | Prisma.UserPolicyOrderByWithRelationInput[]
  cursor?: Prisma.UserPolicyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserPolicyScalarFieldEnum | Prisma.UserPolicyScalarFieldEnum[]
}

/**
 * Policy.reviews
 */
export type Policy$reviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Review
   */
  select?: Prisma.ReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Review
   */
  omit?: Prisma.ReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewInclude<ExtArgs> | null
  where?: Prisma.ReviewWhereInput
  orderBy?: Prisma.ReviewOrderByWithRelationInput | Prisma.ReviewOrderByWithRelationInput[]
  cursor?: Prisma.ReviewWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReviewScalarFieldEnum | Prisma.ReviewScalarFieldEnum[]
}

/**
 * Policy without action
 */
export type PolicyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Policy
   */
  select?: Prisma.PolicySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Policy
   */
  omit?: Prisma.PolicyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyInclude<ExtArgs> | null
}
